// SPDX-FileCopyrightText: 2026 Pharmakos contributors
// SPDX-License-Identifier: GPL-3.0-or-later

//! The world, the named tick phases and the per-tick state hash.
//!
//! # What this world is today, said plainly
//!
//! T2 brought the determinism core; T5 brought the map. The world below carries
//! the hashed tables the skeleton's sim needs — seats, units, beacons,
//! structures, wrecks and the chunk store's per-chunk digests — over a seeded
//! map generated by [`crate::mapgen`] from the rules table's `map` block.
//!
//! * T7 replaces straight-line walking with path following over HPA\*.
//! * T10 brings the Lull / Push / recap runner around this loop.
//! * T11 drives destinations from the playbook interpreter.
//! * T14 fills the economy, the Build mandate, Survey-lite and the programs,
//!   and is the first task to put anything in the voxel phase's edit queue.
//!
//! Every one of those pull requests **moves the hash chain**, and each one owes
//! the explanation (AGENTS.md section 4.8, section 10 item 2). The values marked
//! `PLACEHOLDER (harness)` below are scaffolding those tasks delete, not tuning
//! values: they are not in the rules table because they are not rules.
//!
//! # The phase order is fixed
//!
//! [`PHASE_ORDER`] is the tick, in the order spec section 15 sets out, and
//! [`World::step`] runs exactly it. The order is determinism code: reordering it
//! is a contract change (AGENTS.md section 5).
//!
//! # The hash is full, every tick
//!
//! Item 66: re-hash every table every tick, in declared order, into a **reused**
//! buffer, with the chunk store entering as per-chunk digests. The incremental
//! alternative was measured and rejected — 7.641 of 8 tables are dirty on
//! essentially every tick, so it saves 0.02 % of the gate tick and buys that
//! with a dirty flag on every write site in the sim, forever, on the
//! determinism artefact itself.

use crate::chunks::ChunkDigests;
use crate::encoding::Enc;
use crate::mapgen::{self, MapError};
use crate::math::fixed::{Angle, Fx};
use crate::math::quantity::{Hp, Kw, Money, Tick};
use crate::math::random::{Stream, StreamRng};
use crate::pathing::clusters::Clusters;
use crate::pathing::repair::{RepairReport, Repairer, repair};
use crate::pathing::router::{Router, ServeReport, WalkState};
use crate::pathing::search::Scratch;
use crate::pathing::surface::{StepCosts, Surface};
use crate::rules::RulesTable;
use crate::seams::WorkCounter;
use crate::tables::{
    BeaconTable, Csr, MovementColumns, SeatId, SeatTable, StructureTable, UnitId, UnitKind,
    UnitTable, WreckTable,
};
use crate::voxels::{CHUNK_EDGE, VoxelEdit, VoxelStore};

/// The eleven named phases of a tick, in the order they run.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum Phase {
    /// Rebuild the CSR uniform grid from this tick's positions (T2).
    Broadphase,
    /// Run units' and buildings' built-in programs (T14).
    Programs,
    /// Advance every mover (T2 in its harness form; T7 replaces it with path
    /// following).
    Movement,
    /// Resolve fire and damage (S2).
    Combat,
    /// Apportion per-seat kill credit by largest remainder, ties to the lowest
    /// seat id (T14).
    KillCredit,
    /// Settle supply, draw, the brownout order and dormancy (T14).
    Power,
    /// Hold fabricator orders and fill spend requests by the urgency ladder
    /// (T14).
    Quartermaster,
    /// The playbook interpreter's decision tick, every 250 ms of game time
    /// (T11).
    Decision,
    /// Serve the per-tick repath cap and repair the abstract graph (T7).
    Pathing,
    /// Apply this tick's voxel edits and refresh the chunks they touched (T5).
    Voxels,
    /// Encode the world in declared table order and digest it (T2).
    Hash,
}

/// The tick, in order. Determinism code: see the module docs.
pub const PHASE_ORDER: [Phase; 11] = [
    Phase::Broadphase,
    Phase::Programs,
    Phase::Movement,
    Phase::Combat,
    Phase::KillCredit,
    Phase::Power,
    Phase::Quartermaster,
    Phase::Decision,
    Phase::Pathing,
    Phase::Voxels,
    Phase::Hash,
];

/// PLACEHOLDER (harness): the per-tick work budget the seam starts with. The
/// number becomes meaningful at S5, when the operator's budget is measured in
/// evaluation units (owner).
const HARNESS_WORK_BUDGET: u32 = 1_000_000;

/// PLACEHOLDER (harness): how many voxel edits one tick's queue holds.
///
/// Fixed at construction because nothing in a tick allocates (G3' section 9.17),
/// and sized against item 65's destruction rate — 20 craters a second is one a
/// tick at 20 Hz, and 64 leaves room for a burst without ever growing. S2 sets
/// the real number when combat is the thing filling the queue (owner, at S2).
const HARNESS_EDIT_QUEUE: usize = 64;

/// PLACEHOLDER (harness): the largest radius a broadphase query asks for, in
/// **voxels**. S2's combat phase replaces it with a weapon's range out of the
/// rules table (owner, at S2).
///
/// In voxels because a query radius in cells would make the answer's membership
/// depend on the cell edge, which the rules table declares a non-hashed tuning
/// knob — see [`Csr::collect_in_radius`]. Item 67's sizing rule is the other
/// direction of the same relation: the cell edge is chosen at least the largest
/// query radius so a query touches at most 3 x 3 cells, and 16 voxels is the
/// cell edge `rules/rules.v1.json` currently carries.
pub const BROADPHASE_QUERY_RADIUS_VOXELS: Fx = Fx::from_voxels(16);

/// How to build a world.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct WorldConfig {
    /// The match seed.
    ///
    /// The sim is a pure function of this, the playbooks and the rules hash —
    /// and **the map seed is the match seed**, not a value derived from it.
    /// One number, stated once, so a save that carries the match seed carries
    /// the map with it and a scenario file that names a seed names the map
    /// (`scenarios/skeleton/expand-east.scenario.jsonc`). A derived map seed
    /// would be a second number to keep in step for no gain: the map generator
    /// already draws on its own [`Stream::Map`], which is what keeps its draws
    /// from interleaving with anybody else's (item 50).
    pub match_seed: u64,
    /// How many seats share the match. At most three in v1; the determinism
    /// harness runs more because a wider table is a wider hash. Seat `i`
    /// occupies spawn zone `i`; a seat beyond the map's zones is seated but
    /// unplaced (see [`crate::mapgen`]).
    pub seats: u32,
    /// PLACEHOLDER (harness): how many extra walking units each seat fields on
    /// top of its starting force, so that the hash chain covers a wide table
    /// before T11 and T14 fill one honestly. A real match passes zero. Deleted
    /// when T14 fabricates units for real (owner, at T14).
    pub units_per_seat: u32,
    /// The rules table, an **input** to the sim and never hashed state.
    pub rules: RulesTable,
}

/// The authoritative world: the hashed tables, the derived indexes and the
/// tick loop.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct World {
    // --- hashed state, in declared encoding order ---
    match_seed: u64,
    tick: Tick,
    seats: SeatTable,
    units: UnitTable,
    beacons: BeaconTable,
    structures: StructureTable,
    wrecks: WreckTable,
    chunks: ChunkDigests,

    // --- hashed state, continued: the router (item 62's routes) ---
    router: Router,

    // --- the voxels themselves: hashed only through `chunks` (item 66) ---
    voxels: VoxelStore,

    // --- inputs and derived state: never encoded, never hashed ---
    rules: RulesTable,
    broadphase: Csr,
    /// The HPA\* surface graph. Derived from the chunk store and the cost rows,
    /// rebuilt on a restore rather than carried in a snapshot.
    surface: Surface,
    /// The HPA\* decomposition. Derived, as above.
    clusters: Clusters,
    /// The search's buffers, reused across every query of every tick.
    scratch: Scratch,
    /// The repair's working sets, and the dirty-cluster list the voxel phase
    /// fills.
    repairer: Repairer,
    work: WorkCounter,
    /// What the last tick's repair did. Diagnostic; never hashed.
    repair_report: RepairReport,
    /// What the last tick's serving did. Diagnostic; never hashed.
    serve_report: ServeReport,
    /// Scratch for the arrived-unit list, so a tick's destination draws
    /// allocate nothing.
    arrivals: Vec<u32>,
    /// This tick's voxel edits, drained by [`Phase::Voxels`].
    edits: Vec<VoxelEdit>,
    /// Scratch for a crater's touched-chunk list, so an edit allocates nothing.
    touched: Vec<u32>,
    /// Scratch for broadphase queries, so a query allocates nothing.
    candidates: Vec<u32>,
}

/// Every hashed table of a restored world, handed over in one piece.
///
/// One struct rather than nine arguments because a restore that applies eight
/// of nine tables is not a state this sim has, and a positional argument list
/// nine long is how that happens.
#[derive(Clone, PartialEq, Eq, Debug)]
pub(crate) struct RestoredTables {
    pub(crate) match_seed: u64,
    pub(crate) tick: Tick,
    pub(crate) seats: SeatTable,
    pub(crate) units: UnitTable,
    pub(crate) beacons: BeaconTable,
    pub(crate) structures: StructureTable,
    pub(crate) wrecks: WreckTable,
    pub(crate) voxels: VoxelStore,
    pub(crate) chunks: ChunkDigests,
    pub(crate) router: crate::pathing::router::RestoredRouter,
}

impl World {
    /// Generate the map for `config.match_seed` and build the world on it.
    ///
    /// The generator places each occupied seat's core beacon, commander and
    /// starting drones; the harness's `units_per_seat` extra walkers are
    /// appended after them, so unit ids stay dense and in seat order.
    ///
    /// # Errors
    ///
    /// Returns the [`MapError`] the generator reported, or
    /// [`MapError::Unindexable`] when the rules table cannot describe a
    /// broadphase grid for the resulting unit count — both of which are
    /// rules-table mistakes caught once, here, rather than every tick.
    pub fn new(config: &WorldConfig) -> Result<World, MapError> {
        let generated = mapgen::generate(config.match_seed, &config.rules, config.seats)?;
        let extent = config.rules.map_size_voxels();
        let max_x = i16::try_from(extent.first().copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);
        let max_y = i16::try_from(extent.get(1).copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);

        let harness_units = config.seats.saturating_mul(config.units_per_seat);
        let starting = u32::try_from(generated.starting_units.len()).unwrap_or(u32::MAX);
        let unit_count = starting.saturating_add(harness_units);

        let mut seats = SeatTable::with_capacity(config.seats);
        let mut seat_index: u32 = 0;
        while seat_index < config.seats {
            let at = usize::try_from(seat_index).unwrap_or(usize::MAX);
            seats.push(
                SeatId::new(u8::try_from(seat_index).unwrap_or(u8::MAX)),
                generated
                    .seat_treasury
                    .get(at)
                    .copied()
                    .unwrap_or(Money::ZERO),
                generated.seat_supply.get(at).copied().unwrap_or(Kw::ZERO),
                generated.seat_draw.get(at).copied().unwrap_or(Kw::ZERO),
            );
            seat_index = seat_index.saturating_add(1);
        }

        let units = fill_unit_table(config, &generated, unit_count, [max_x, max_y]);

        let mut voxels = generated.voxels;
        let chunk_total = voxels.chunk_count();
        let mut chunks = ChunkDigests::new(chunk_total);
        voxels.settle_all(&mut chunks);

        let Some(broadphase) = Csr::new(
            [0, 0],
            [
                extent.first().copied().unwrap_or(0),
                extent.get(1).copied().unwrap_or(0),
            ],
            config.rules.csr_cell_size_voxels(),
            unit_count,
        ) else {
            return Err(MapError::Unindexable { units: unit_count });
        };

        let cluster_voxels = config.rules.hpa_cluster_voxels();
        let Some(surface) = Surface::new(&voxels, StepCosts::from_rules(&config.rules)) else {
            return Err(MapError::BadExtent {
                size: voxels.size(),
            });
        };
        let Some((clusters, scratch)) = build_graph(&surface, cluster_voxels) else {
            return Err(MapError::Unclusterable { cluster_voxels });
        };
        let mut router = Router::new(unit_count, &config.rules);
        let mut unit = 0;
        while unit < unit_count {
            // Every unit starts by asking for a route: the harness's walkers
            // have a destination drawn on the map, and a starting unit's
            // destination is where it already stands, which the router answers
            // with "arrived" and the tick answers with a fresh destination.
            router.request(unit);
            unit = unit.saturating_add(1);
        }

        Ok(World {
            match_seed: config.match_seed,
            tick: Tick::ZERO,
            seats,
            units,
            beacons: generated.beacons,
            structures: StructureTable::with_capacity(0),
            wrecks: WreckTable::with_capacity(0),
            chunks,
            router,
            voxels,
            rules: config.rules.clone(),
            broadphase,
            repairer: Repairer::new(clusters.cluster_count()),
            surface,
            clusters,
            scratch,
            work: WorkCounter::with_budget(HARNESS_WORK_BUDGET),
            repair_report: RepairReport::default(),
            serve_report: ServeReport::default(),
            arrivals: Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0)),
            edits: Vec::with_capacity(HARNESS_EDIT_QUEUE),
            // Sized to the whole map rather than to the queue: one crater can
            // touch more chunks than the queue holds edits, and a scratch
            // buffer that has to grow is an allocation inside a tick.
            touched: Vec::with_capacity(usize::try_from(chunk_total).unwrap_or(0)),
            candidates: Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0)),
        })
    }

    /// The match seed, which is also the map seed ([`WorldConfig::match_seed`]).
    #[must_use]
    pub const fn match_seed(&self) -> u64 {
        self.match_seed
    }

    /// The current tick.
    #[must_use]
    pub const fn tick(&self) -> Tick {
        self.tick
    }

    /// The seat table.
    #[must_use]
    pub const fn seats(&self) -> &SeatTable {
        &self.seats
    }

    /// The unit table.
    #[must_use]
    pub const fn units(&self) -> &UnitTable {
        &self.units
    }

    /// The beacon table.
    #[must_use]
    pub const fn beacons(&self) -> &BeaconTable {
        &self.beacons
    }

    /// The structure table.
    #[must_use]
    pub const fn structures(&self) -> &StructureTable {
        &self.structures
    }

    /// The wreck table.
    #[must_use]
    pub const fn wrecks(&self) -> &WreckTable {
        &self.wrecks
    }

    /// The chunk store's digests.
    #[must_use]
    pub const fn chunks(&self) -> &ChunkDigests {
        &self.chunks
    }

    /// The chunk store's digests, for a test to perturb.
    ///
    /// The voxel phase refreshes these through [`VoxelStore::settle`]; nothing
    /// in the tick reaches for this.
    pub const fn chunks_mut(&mut self) -> &mut ChunkDigests {
        &mut self.chunks
    }

    /// The voxels.
    ///
    /// Read-only by design: the way to change a voxel is
    /// [`World::request_voxel_edit`], so every write lands in the voxel phase
    /// and every digest is refreshed in one place.
    #[must_use]
    pub const fn voxels(&self) -> &VoxelStore {
        &self.voxels
    }

    /// The rules table this world runs under. An input, never hashed state.
    #[must_use]
    pub const fn rules(&self) -> &RulesTable {
        &self.rules
    }

    /// The broadphase index. Derived, never hashed.
    #[must_use]
    pub const fn broadphase(&self) -> &Csr {
        &self.broadphase
    }

    /// The pathing graph's surface. Derived from the chunk store.
    #[must_use]
    pub const fn surface(&self) -> &Surface {
        &self.surface
    }

    /// The HPA\* decomposition. Derived from the surface.
    #[must_use]
    pub const fn clusters(&self) -> &Clusters {
        &self.clusters
    }

    /// The router: routes, walk states and the repath queue.
    #[must_use]
    pub const fn router(&self) -> &Router {
        &self.router
    }

    /// The search scratch, so a caller outside the tick — the gateway asking
    /// for an estimate, a test, a bench — can run a query without allocating a
    /// second set of dense arrays.
    ///
    /// Nothing in it is state: a query leaves the scratch different and the
    /// world identical, which `a_query_does_not_change_the_world` asserts.
    pub const fn scratch_mut(&mut self) -> &mut Scratch {
        &mut self.scratch
    }

    /// What the last tick's graph repair did.
    #[must_use]
    pub const fn repair_report(&self) -> RepairReport {
        self.repair_report
    }

    /// What the last tick's repath serving did.
    #[must_use]
    pub const fn serve_report(&self) -> ServeReport {
        self.serve_report
    }

    /// How many units are waiting for a repath right now.
    #[must_use]
    pub fn repath_backlog(&self) -> u32 {
        self.router.backlog()
    }

    /// How many units are parked as sealed in right now.
    ///
    /// The report half of item 60's "park and report": the seat learns through
    /// this until T10's event bus exists to carry it as an event.
    #[must_use]
    pub fn sealed_units(&self) -> u32 {
        let mut count: u32 = 0;
        let mut unit: u32 = 0;
        while unit < self.router.len() {
            if self.router.state(unit) == WalkState::Sealed {
                count = count.saturating_add(1);
            }
            unit = unit.saturating_add(1);
        }
        count
    }

    /// This tick's work counter. Not hashed today; see [`WorkCounter`].
    #[must_use]
    pub const fn work(&self) -> WorkCounter {
        self.work
    }

    /// This tick's work counter, to charge against.
    ///
    /// Nothing in the tick charges it yet — the phases that will are T11's and
    /// S5's. It is reachable now so that
    /// `tests/determinism.rs`'s `the_work_counter_is_not_in_the_state_encoding`
    /// can prove the counter stays out of the hash.
    pub const fn work_mut(&mut self) -> &mut WorkCounter {
        &mut self.work
    }

    /// Ask for a voxel edit. Returns `false` when this tick's queue is full.
    ///
    /// **The order a filler owes.** The queue is applied in the order it was
    /// filled, so a phase that fills it must do so in an order that is itself
    /// deterministic — every sort key ending in a unique id, as everywhere else
    /// (item 62). Nothing fills it yet: combat's craters are S2's and
    /// construction's sets are T14's, and each of those phases already walks its
    /// own table in id order, which is the order the queue will inherit.
    ///
    /// A full queue drops nothing silently: the `false` is the report, and a
    /// caller that cannot afford to lose an edit must handle it.
    pub fn request_voxel_edit(&mut self, edit: VoxelEdit) -> bool {
        if self.edits.len() >= HARNESS_EDIT_QUEUE {
            return false;
        }
        self.edits.push(edit);
        true
    }

    /// How many edits are queued for this tick's voxel phase.
    #[must_use]
    pub fn queued_voxel_edits(&self) -> usize {
        self.edits.len()
    }

    /// Advance one tick and return the tick's state hash.
    ///
    /// `enc` is the caller's buffer, reused across ticks: that is what makes a
    /// tick allocation-free (G3' section 9.17), and `tests/allocations.rs`
    /// asserts it.
    pub fn step(&mut self, enc: &mut Enc) -> u64 {
        self.tick = self.tick.next().unwrap_or(self.tick);
        self.work.reset();
        let mut hash = 0;
        for phase in PHASE_ORDER {
            match phase {
                Phase::Broadphase => self.phase_broadphase(),
                Phase::Programs => self.phase_programs(),
                Phase::Movement => self.phase_movement(),
                Phase::Combat => self.phase_combat(),
                Phase::KillCredit => self.phase_kill_credit(),
                Phase::Power => self.phase_power(),
                Phase::Quartermaster => self.phase_quartermaster(),
                Phase::Decision => self.phase_decision(),
                Phase::Pathing => self.phase_pathing(),
                Phase::Voxels => self.phase_voxels(),
                Phase::Hash => hash = self.phase_hash(enc),
            }
        }
        hash
    }

    /// Rebuild the CSR uniform grid by counting sort (item 67).
    ///
    /// [`Csr::rebuild`] answers `false` when the unit table is larger than the
    /// grid it was built for, and leaves the grid **empty** — so swallowing
    /// that answer buys a world that hashes correctly and then queries an empty
    /// index for the rest of the match. [`World::new`] and
    /// [`World::restore_tables`] are the only two ways to get a grid, and both
    /// size it to the unit table, so a `false` here is a construction bug and
    /// the assertion is how it surfaces at the tick that caused it.
    fn phase_broadphase(&mut self) {
        let rebuilt = self.broadphase.rebuild(self.units.positions());
        debug_assert!(
            rebuilt,
            "the unit table outgrew the broadphase grid; every query from here on would come \
             back empty"
        );
    }

    /// Units' and buildings' built-in programs. **Empty: T14 fills it** (move,
    /// build, mine and scout).
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_programs(&mut self) {}

    /// Advance every mover along the route it is following.
    ///
    /// Item 90's accumulator, in one sentence: a walker adds its kind's
    /// `cost_per_second` to an integer accumulator each tick and spends one
    /// cost unit per 20 accumulated, so it arrives on
    /// `ceil(cost * 20 / cost_per_second)` — the tick the estimator promised.
    /// No float, no division that rounds a speed down, and no wandering: a unit
    /// walks the route [`Phase::Pathing`] gave it, one legal step at a time,
    /// and asks for another the moment a step stops being legal.
    ///
    /// What is *not* here is where a unit decides to go. The harness still
    /// draws a destination at random from [`Stream::Spawn`] when a unit arrives
    /// (see [`World::draw_new_destinations`]); T11's interpreter replaces that
    /// with the playbook, and the walking below does not change when it does.
    fn phase_movement(&mut self) {
        let MovementColumns {
            ids: _,
            seats: _,
            kinds,
            hit_points,
            positions,
            destinations: _,
            headings,
        } = self.units.movement_columns();
        self.router
            .advance(&self.surface, kinds, hit_points, positions, headings);
    }

    /// Fire and damage. **Empty: S2 fills it.** `Stream::Combat` is reserved
    /// for it and is drawn from nowhere else.
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; S2 fills the body"
    )]
    const fn phase_combat(&mut self) {}

    /// Per-seat kill-credit counters, at most three per asset, apportioned by
    /// largest remainder with ties to the lowest seat id. **Empty: T14 fills
    /// it**, and hashes the counters from the day they exist even though combat
    /// is S2 — a field that affects behaviour and is not hashed is a latent
    /// desync.
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_kill_credit(&mut self) {}

    /// Supply, draw, brownout order, dormancy, the revive margin. **Empty: T14
    /// fills it.**
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_power(&mut self) {}

    /// Hold fabricator orders, then the brownout order; fill spend requests by
    /// the urgency ladder, round-robin within a band. **Empty: T14 fills it**,
    /// behind the `Quartermaster` trait that is also T14's.
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_quartermaster(&mut self) {}

    /// The interpreter's decision tick, one per 250 ms of game time. **Empty:
    /// T11 fills it.**
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T11 fills the body"
    )]
    const fn phase_decision(&mut self) {}

    /// Repair the abstract graph, re-arm the units it may have freed, and serve
    /// the repath cap round-robin by `(seat, beacon, unit)`.
    ///
    /// The order is item 60's, and it is the reason a route is never planned
    /// over terrain that has moved: the repair runs **before** any repath this
    /// tick, and the columns the search reads were refreshed in the same tick
    /// the voxels changed (see [`World::phase_voxels`]). The one lag that does
    /// exist is a cluster's *entrances*, which are repaired here on the tick
    /// after the edit because [`PHASE_ORDER`] puts `Pathing` before `Voxels` —
    /// and that lag can only withhold routes, never invent one, because every
    /// step of a route is validated against the live columns as it is walked.
    fn phase_pathing(&mut self) {
        let report = repair(
            &self.surface,
            &mut self.clusters,
            &mut self.scratch,
            &mut self.repairer,
        );
        if report.dirty > 0 {
            self.router.rearm_sealed(
                &self.surface,
                &self.clusters,
                self.repairer.repaired(),
                self.units.positions(),
                self.units.destinations(),
            );
        }
        self.serve_report = self.router.serve(
            &self.surface,
            &self.clusters,
            &mut self.scratch,
            self.units.positions(),
            self.units.destinations(),
            self.rules.repath_cap_per_tick(),
        );
        self.repair_report = report;
        self.draw_new_destinations();
    }

    /// Give every unit that reached the end of a route somewhere new to be.
    ///
    /// PLACEHOLDER (harness): the destination is drawn from [`Stream::Spawn`] at
    /// `(tick, seat, unit id)`, which is the wandering T2 introduced so that the
    /// hash chain covers a moving table. T11's playbook interpreter is what
    /// replaces it with a destination somebody chose (owner, at T11).
    fn draw_new_destinations(&mut self) {
        if self.router.arrived().is_empty() {
            return;
        }
        self.arrivals.clear();
        self.arrivals.extend_from_slice(self.router.arrived());
        let match_seed = self.match_seed;
        let tick = self.tick.raw();
        let extent = self.rules.map_size_voxels();
        let max_x = i16::try_from(extent.first().copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);
        let max_y = i16::try_from(extent.get(1).copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);
        let mut at = 0;
        while at < self.arrivals.len() {
            let Some(unit) = self.arrivals.get(at).copied() else {
                break;
            };
            at = at.saturating_add(1);
            let index = usize::try_from(unit).unwrap_or(usize::MAX);
            let seat = self.units.seats().get(index).copied().unwrap_or(0);
            let id = self.units.ids().get(index).copied().unwrap_or(0);
            let mut rng = StreamRng::new(match_seed, Stream::Spawn, tick, seat, id);
            let point = ground_point(&self.voxels, &mut rng, max_x, max_y);
            if let Some(slot) = self.units.destinations_mut().get_mut(index) {
                *slot = point;
            }
            self.router.request(unit);
        }
    }

    /// Apply this tick's voxel edits, then refresh the digest of every chunk
    /// they touched, in ascending chunk index.
    ///
    /// The queue is drained in the order it was filled (see
    /// [`World::request_voxel_edit`]); the *digests* are refreshed in chunk
    /// order regardless, because that is the order the canonical encoder walks
    /// them in and the only order the hash can see.
    ///
    /// The crater's touched-chunk list is written into the world's own scratch
    /// and then dropped: the phase does not need it, because
    /// [`VoxelStore::settle`] already walks every chunk any edit marked. It is
    /// passed rather than made optional so that the primitive has one signature,
    /// and it is a field rather than a local so that a crater inside a tick
    /// allocates nothing.
    fn phase_voxels(&mut self) {
        // The edit list and the touched scratch are separate fields from the
        // store, so draining one while writing the other borrows nothing twice.
        let edits = core::mem::take(&mut self.edits);
        let mut touched = core::mem::take(&mut self.touched);
        for edit in &edits {
            match *edit {
                VoxelEdit::Set { at, material } => {
                    self.voxels.set(at, material);
                }
                VoxelEdit::Crater { centre, radius } => {
                    self.voxels.crater(centre, radius, &mut touched);
                }
            }
        }
        self.voxels.settle(&mut self.chunks);
        // The pathing graph's columns are refreshed in the same phase that
        // changed the bytes, so a walker's next step is validated against the
        // terrain as it is; the *clusters* the edit dirtied are repaired at the
        // next tick's `Pathing` phase, which is where the entrance rescan and
        // the one connectivity rebuild live (item 60).
        let mut at = 0;
        while at < self.voxels.settled().len() {
            let Some(chunk) = self.voxels.settled().get(at).copied() else {
                break;
            };
            at = at.saturating_add(1);
            self.surface.refresh_chunk(&self.voxels, chunk);
            mark_chunk_clusters(&self.voxels, &self.clusters, &mut self.repairer, chunk);
        }
        touched.clear();
        self.touched = touched;
        self.edits = edits;
        self.edits.clear();
    }

    /// Encode the world and digest it.
    fn phase_hash(&self, enc: &mut Enc) -> u64 {
        self.encode(enc);
        enc.finish()
    }

    /// Append the world to the canonical encoding, in **declared table order**.
    ///
    /// The order below is the contract. Adding a table means appending it here,
    /// adding it to the snapshot round-trip and re-blessing the goldens, all in
    /// the same pull request (AGENTS.md section 4.8).
    ///
    /// 1. header — match seed, tick
    /// 2. seats
    /// 3. units
    /// 4. beacons
    /// 5. structures
    /// 6. wrecks
    /// 7. chunk digests
    /// 8. the router — per unit: walk state, speed accumulator, route length,
    ///    route cursor, whether the route is partial, and the **route's
    ///    digest**; then the round-robin cursor. The route's nodes reach the
    ///    hash through that digest for the reason the chunk store's bytes reach
    ///    it through per-chunk digests (item 66): a column that grows with the
    ///    map does not belong in a per-tick encoding. The nodes themselves
    ///    travel in the snapshot, and a restore that produced a different route
    ///    would show up here as a moved digest.
    ///
    /// The rules table, the voxel bytes, the broadphase and the work counter
    /// are **not** here. The first, third and fourth are inputs or derived
    /// state, and `tests/determinism.rs` asserts that changing a performance
    /// knob leaves the chain byte-identical; the voxels reach the hash through
    /// their per-chunk digests and never as bytes (item 66).
    pub fn encode(&self, enc: &mut Enc) {
        enc.clear();
        enc.u64(self.match_seed);
        enc.u32(self.tick.raw());

        enc.len(self.seats.len());
        for (index, seat) in self.seats.seats().iter().enumerate() {
            enc.u8(*seat);
            enc.i64(
                self.seats
                    .treasuries()
                    .get(index)
                    .copied()
                    .unwrap_or(Money::ZERO)
                    .raw(),
            );
            enc.i32(
                self.seats
                    .supplies()
                    .get(index)
                    .copied()
                    .unwrap_or(Kw::ZERO)
                    .raw(),
            );
            enc.i32(
                self.seats
                    .draws()
                    .get(index)
                    .copied()
                    .unwrap_or(Kw::ZERO)
                    .raw(),
            );
        }

        enc.len(self.units.len());
        let positions = self.units.positions();
        let destinations = self.units.destinations();
        let headings = self.units.headings();
        let hit_points = self.units.hit_points();
        let kinds = self.units.kinds();
        for (index, id) in self.units.ids().iter().enumerate() {
            enc.u32(*id);
            enc.u8(self.units.seats().get(index).copied().unwrap_or(0));
            enc.u8(kinds.get(index).copied().unwrap_or(0));
            encode_point(enc, positions.get(index));
            encode_point(enc, destinations.get(index));
            enc.u16(headings.get(index).copied().unwrap_or(Angle::ZERO).raw());
            enc.i32(hit_points.get(index).copied().unwrap_or(Hp::ZERO).raw());
        }

        enc.len(self.beacons.len());
        let beacon_positions = self.beacons.positions();
        let mandates = self.beacons.mandates();
        let programs = self.beacons.programs();
        let beacon_hp = self.beacons.hit_points();
        let dormant = self.beacons.dormant();
        for (index, id) in self.beacons.ids().iter().enumerate() {
            enc.u32(*id);
            enc.u8(self.beacons.seats().get(index).copied().unwrap_or(0));
            encode_point(enc, beacon_positions.get(index));
            enc.u8(mandates.get(index).copied().unwrap_or(0));
            enc.u32(programs.get(index).copied().unwrap_or(0));
            enc.i32(beacon_hp.get(index).copied().unwrap_or(Hp::ZERO).raw());
            enc.bool(dormant.get(index).copied().unwrap_or(false));
        }

        enc.len(self.structures.len());
        let structure_positions = self.structures.positions();
        let structure_kinds = self.structures.kinds();
        let structure_hp = self.structures.hit_points();
        let homes = self.structures.homes();
        for (index, id) in self.structures.ids().iter().enumerate() {
            enc.u32(*id);
            enc.u8(self.structures.seats().get(index).copied().unwrap_or(0));
            enc.u8(structure_kinds.get(index).copied().unwrap_or(0));
            encode_point(enc, structure_positions.get(index));
            enc.i32(structure_hp.get(index).copied().unwrap_or(Hp::ZERO).raw());
            enc.u32(homes.get(index).copied().unwrap_or(u32::MAX));
        }

        enc.len(self.wrecks.len());
        let wreck_positions = self.wrecks.positions();
        let salvages = self.wrecks.salvages();
        for (index, id) in self.wrecks.ids().iter().enumerate() {
            enc.u32(*id);
            encode_point(enc, wreck_positions.get(index));
            enc.i64(salvages.get(index).copied().unwrap_or(Money::ZERO).raw());
        }

        self.chunks.encode(enc);
        self.router.encode(enc);
    }

    /// The per-tick state hash, allocating its own encoder.
    ///
    /// The tick loop uses [`World::step`]'s reused buffer instead; this form is
    /// for tests, snapshots and one-off checks.
    #[must_use]
    pub fn state_hash(&self) -> u64 {
        let mut enc = Enc::with_capacity(16 * 1024);
        self.encode(&mut enc);
        enc.finish()
    }

    /// The ids within `radius` **voxels** of `centre`, sorted ascending, in the
    /// world's own scratch buffer.
    ///
    /// Allocation-free after construction, and independent of the broadphase's
    /// cell size in both membership and order — see
    /// [`Csr::collect_in_radius`], which does the exact range test the grid
    /// itself cannot.
    pub fn candidates_near(&mut self, centre: [Fx; 3], radius: Fx) -> &[u32] {
        let mut scratch = core::mem::take(&mut self.candidates);
        self.broadphase
            .collect_in_radius(self.units.positions(), centre, radius, &mut scratch);
        self.candidates = scratch;
        &self.candidates
    }

    /// Replace the hashed tables from a restored snapshot, and **resize the
    /// derived index to match them**.
    ///
    /// The broadphase is sized for a unit count at construction. A snapshot
    /// holding more units than the receiving world was built for would
    /// otherwise restore cleanly, hash correctly, and leave every later
    /// broadphase query empty — see [`World::phase_broadphase`]. So the grid is
    /// rebuilt here, for the restored count, before anything is written.
    ///
    /// Returns `false` and changes **nothing** when the grid cannot be built
    /// for the restored world, the same answer [`World::new`] gives for the
    /// same reason. A half-applied restore is not a state this sim has.
    ///
    /// Crate-internal: [`crate::snapshot`] is the only caller, so a restore
    /// cannot skip the version check.
    pub(crate) fn restore_tables(&mut self, restored: RestoredTables) -> bool {
        let unit_count = restored.units.len();
        let extent = self.rules.map_size_voxels();
        let Some(broadphase) = Csr::new(
            [0, 0],
            [
                extent.first().copied().unwrap_or(0),
                extent.get(1).copied().unwrap_or(0),
            ],
            self.rules.csr_cell_size_voxels(),
            unit_count,
        ) else {
            return false;
        };
        // The router is restored before anything is written, for the same
        // reason the grid is built first: a file whose route columns disagree
        // must leave the world exactly as it was.
        if !self.router.restore(restored.router) {
            return false;
        }

        self.match_seed = restored.match_seed;
        self.tick = restored.tick;
        self.seats = restored.seats;
        self.units = restored.units;
        self.beacons = restored.beacons;
        self.structures = restored.structures;
        self.wrecks = restored.wrecks;
        self.voxels = restored.voxels;
        self.chunks = restored.chunks;
        self.broadphase = broadphase;
        // The pathing graph is derived, so it is rebuilt from the restored
        // store rather than carried in the file — and `tests/pathing.rs`'s
        // `a_restored_world_rebuilds_the_graph_it_was_saved_with` is what makes
        // "derived" a checked claim rather than a convenient one.
        self.surface.refresh_all(&self.voxels);
        self.clusters.rebuild_all(&self.surface, &mut self.scratch);
        self.repairer = Repairer::new(self.clusters.cluster_count());
        self.arrivals = Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0));
        self.repair_report = RepairReport::default();
        self.serve_report = ServeReport::default();
        self.edits.clear();
        self.touched = Vec::with_capacity(usize::try_from(self.voxels.chunk_count()).unwrap_or(0));
        // The query scratch is sized the same way, and for the same reason: a
        // query that has to grow its buffer is an allocation inside a tick.
        self.candidates = Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0));
        true
    }
}

/// The unit table: the generator's starting force first, then the harness's
/// extra walkers, seat by seat.
///
/// One pass, in that order, so unit ids stay **dense and in seat order** —
/// which is what lets [`Csr`] use a row index as an id and what makes every
/// sort key that ends in a unit id a total order (item 62).
fn fill_unit_table(
    config: &WorldConfig,
    generated: &crate::mapgen::GeneratedMap,
    capacity: u32,
    extent: [i16; 2],
) -> UnitTable {
    let mut units = UnitTable::with_capacity(capacity);
    let mut next_id: u32 = 0;
    for unit in &generated.starting_units {
        // A starting unit begins where it stands: the harness walk gives it a
        // destination the moment it notices it has arrived.
        units.push(
            UnitId::new(next_id),
            unit.seat,
            unit.kind,
            unit.at,
            unit.at,
            unit.hp,
        );
        next_id = next_id.saturating_add(1);
    }

    // PLACEHOLDER (harness): the extra walkers are raiders because a raider is
    // the cheapest kind with a rules-table HP row that is not part of a seat's
    // starting force, so they cannot be mistaken for one. T14 deletes them
    // along with `WorldConfig::units_per_seat`.
    let walker_hp = config
        .rules
        .unit_hp(UnitKind::Raider)
        .unwrap_or(Hp::new(100));
    let max_x = extent.first().copied().unwrap_or(0);
    let max_y = extent.get(1).copied().unwrap_or(0);
    let mut seat_index: u32 = 0;
    while seat_index < config.seats {
        let seat = SeatId::new(u8::try_from(seat_index).unwrap_or(u8::MAX));
        let mut n: u32 = 0;
        while n < config.units_per_seat {
            let mut rng = StreamRng::new(
                config.match_seed,
                Stream::Spawn,
                Tick::ZERO.raw(),
                seat.raw(),
                next_id,
            );
            let pos = ground_point(&generated.voxels, &mut rng, max_x, max_y);
            let dest = ground_point(&generated.voxels, &mut rng, max_x, max_y);
            units.push(
                UnitId::new(next_id),
                seat,
                UnitKind::Raider,
                pos,
                dest,
                walker_hp,
            );
            next_id = next_id.saturating_add(1);
            n = n.saturating_add(1);
        }
        seat_index = seat_index.saturating_add(1);
    }
    units
}

/// Build the pathing graph and the scratch it is searched with.
///
/// The scratch has to be sized before the decomposition exists — building the
/// intra edges is itself a search — so [`Scratch::for_map`] does that
/// arithmetic from the map and the cluster edge, and the decomposition is
/// checked against it below.
///
/// `None` when the cluster edge cannot decompose this map, which the caller
/// reports as [`MapError::Unclusterable`].
fn build_graph(surface: &Surface, cluster_voxels: i32) -> Option<(Clusters, Scratch)> {
    let mut scratch = Scratch::for_map(surface, cluster_voxels)?;
    let clusters = Clusters::new(surface, cluster_voxels, &mut scratch)?;
    debug_assert_eq!(
        clusters.abstract_capacity(),
        Scratch::abstract_capacity_for(surface, cluster_voxels).unwrap_or(0),
        "the scratch was sized for a different abstract numbering than the decomposition uses"
    );
    Some((clusters, scratch))
}

/// Mark every cluster a settled chunk's footprint overlaps.
///
/// At the decided cluster edge of 32 a chunk footprint *is* a cluster (item 58),
/// and this loop is one iteration. It is written as a loop anyway because the
/// cluster edge is a rules-table row and the cluster-size sweep in
/// `tests/pathing.rs` runs the decomposition at 16 and 64, where a chunk covers
/// four clusters or a quarter of one.
fn mark_chunk_clusters(
    voxels: &VoxelStore,
    clusters: &Clusters,
    repairer: &mut Repairer,
    chunk: u32,
) {
    let Some(origin) = voxels.chunk_origin(chunk) else {
        return;
    };
    let edge = i32::try_from(CHUNK_EDGE).unwrap_or(32);
    let size = clusters.size().max(1);
    let x0 = origin.first().copied().unwrap_or(0);
    let y0 = origin.get(1).copied().unwrap_or(0);
    let mut cy = y0.div_euclid(size);
    while cy <= y0.saturating_add(edge.saturating_sub(1)).div_euclid(size) {
        let mut cx = x0.div_euclid(size);
        while cx <= x0.saturating_add(edge.saturating_sub(1)).div_euclid(size) {
            if let Some(cluster) = clusters.cluster_index(cx, cy)
                && let Ok(tag) = u16::try_from(cluster)
            {
                repairer.mark(tag);
            }
            cx = cx.saturating_add(1);
        }
        cy = cy.saturating_add(1);
    }
}

fn encode_point(enc: &mut Enc, point: Option<&[Fx; 3]>) {
    let p = point.copied().unwrap_or([Fx::ZERO; 3]);
    for axis in p {
        enc.i32(axis.raw());
    }
}

/// A point drawn uniformly over the map footprint, standing on the surface of
/// whatever column it landed in.
fn ground_point(voxels: &VoxelStore, rng: &mut StreamRng, max_x: i16, max_y: i16) -> [Fx; 3] {
    let x = rng.range_i32(0, i32::from(max_x));
    let y = rng.range_i32(0, i32::from(max_y));
    let z = voxels.standing_z(x, y);
    [
        Fx::from_voxels(i16::try_from(x).unwrap_or(0)),
        Fx::from_voxels(i16::try_from(y).unwrap_or(0)),
        Fx::from_voxels(i16::try_from(z).unwrap_or(0)),
    ]
}
