// SPDX-FileCopyrightText: 2026 Pharmakos contributors
// SPDX-License-Identifier: GPL-3.0-or-later

//! The world, the named tick phases and the per-tick state hash.
//!
//! # What this world is today, said plainly
//!
//! T2 brought the determinism core; T5 brought the map. The world below carries
//! the hashed tables the skeleton's sim needs — seats, units, beacons,
//! structures, wrecks and the chunk store's per-chunk digests — over a seeded
//! map generated by [`crate::mapgen`] from the rules table's `map` block.
//!
//! * T7 replaces straight-line walking with path following over HPA\*.
//! * T10 brings the Lull / Push / recap runner around this loop.
//! * T11 drives destinations from the playbook interpreter.
//! * T14 fills the economy, the Build mandate, Survey-lite and the programs,
//!   and is the first task to put anything in the voxel phase's edit queue.
//!
//! Every one of those pull requests **moves the hash chain**, and each one owes
//! the explanation (AGENTS.md section 4.8, section 10 item 2). The values marked
//! `PLACEHOLDER (harness)` below are scaffolding those tasks delete, not tuning
//! values: they are not in the rules table because they are not rules.
//!
//! # The phase order is fixed
//!
//! [`PHASE_ORDER`] is the tick, in the order spec section 15 sets out, and
//! [`World::step`] runs exactly it. The order is determinism code: reordering it
//! is a contract change (AGENTS.md section 5).
//!
//! # The hash is full, every tick
//!
//! Item 66: re-hash every table every tick, in declared order, into a **reused**
//! buffer, with the chunk store entering as per-chunk digests. The incremental
//! alternative was measured and rejected — 7.641 of 8 tables are dirty on
//! essentially every tick, so it saves 0.02 % of the gate tick and buys that
//! with a dirty flag on every write site in the sim, forever, on the
//! determinism artefact itself.

use crate::chunks::ChunkDigests;
use crate::encoding::Enc;
use crate::events::{EVENT_BUS_CAPACITY, Emission, Event, EventBus, EventKind};
use crate::knowledge::{AssetId, Position};
use crate::mapgen::{self, MapError};
use crate::math::fixed::{Angle, Fx, Sq};
use crate::math::quantity::{Hp, Kw, Money, Ms, Tick};
use crate::math::random::{Stream, StreamRng};
use crate::pathing::clusters::Clusters;
use crate::pathing::repair::{RepairReport, Repairer, repair};
use crate::pathing::router::{Router, ServeReport, WalkState};
use crate::pathing::search::Scratch;
use crate::pathing::surface::{StepCosts, Surface};
use crate::rules::RulesTable;
use crate::runner::{MatchEndReason, MatchPhase, MatchSettings, MatchState};
use crate::seams::WorkCounter;
use crate::tables::{
    BeaconId, BeaconTable, Csr, MovementColumns, NO_RESPAWN, NOT_ELIMINATED, SeatId, SeatTable,
    StructureId, StructureTable, UnitId, UnitKind, UnitTable, WreckTable,
};
use crate::voxels::{CHUNK_EDGE, VoxelEdit, VoxelStore};

/// The twelve named phases of a tick, in the order they run.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum Phase {
    /// Rebuild the CSR uniform grid from this tick's positions (T2).
    Broadphase,
    /// Run units' and buildings' built-in programs (T14).
    Programs,
    /// Advance every mover (T2 in its harness form; T7 replaces it with path
    /// following).
    Movement,
    /// Resolve fire and damage (S2).
    Combat,
    /// Apportion per-seat kill credit by largest remainder, ties to the lowest
    /// seat id (T14).
    KillCredit,
    /// Settle supply, draw, the brownout order and dormancy (T14).
    Power,
    /// Hold fabricator orders and fill spend requests by the urgency ladder
    /// (T14).
    Quartermaster,
    /// The playbook interpreter's decision tick, every 250 ms of game time
    /// (T11).
    Decision,
    /// Serve the per-tick repath cap and repair the abstract graph (T7).
    Pathing,
    /// Apply this tick's voxel edits and refresh the chunks they touched (T5).
    Voxels,
    /// Settle the match: respawns, local elimination, seat elimination, the
    /// one-tick match-end rule and the segment's end (T10).
    ///
    /// **After everything that can kill and before the hash**, which is the
    /// only place it can be: elimination is a consequence of this tick's
    /// damage, and the phase that acts on it has to run after the phases that
    /// deal it, while the tick whose hash records the consequence has to be the
    /// tick the consequence happened on (item 16's one-tick rule is a claim
    /// about a tick, so it has to be true of that tick's hash).
    Match,
    /// Encode the world in declared table order and digest it (T2).
    Hash,
}

/// The tick, in order. Determinism code: see the module docs.
pub const PHASE_ORDER: [Phase; 12] = [
    Phase::Broadphase,
    Phase::Programs,
    Phase::Movement,
    Phase::Combat,
    Phase::KillCredit,
    Phase::Power,
    Phase::Quartermaster,
    Phase::Decision,
    Phase::Pathing,
    Phase::Voxels,
    Phase::Match,
    Phase::Hash,
];

/// PLACEHOLDER (harness): the per-tick work budget the seam starts with. The
/// number becomes meaningful at S5, when the operator's budget is measured in
/// evaluation units (owner).
const HARNESS_WORK_BUDGET: u32 = 1_000_000;

/// PLACEHOLDER (harness): how many voxel edits one tick's queue holds.
///
/// Fixed at construction because nothing in a tick allocates (G3' section 9.17),
/// and sized against item 65's destruction rate — 20 craters a second is one a
/// tick at 20 Hz, and 64 leaves room for a burst without ever growing. S2 sets
/// the real number when combat is the thing filling the queue (owner, at S2).
const HARNESS_EDIT_QUEUE: usize = 64;

/// PLACEHOLDER (harness): how many damage orders one tick's queue holds.
///
/// Fixed at construction for the reason the edit queue is: nothing in a tick
/// allocates (G3' section 9.17). Sized above the edit queue because one crater
/// can hurt several things, and S2 sets the real number when combat is the
/// thing filling it (owner, at S2).
const HARNESS_DAMAGE_QUEUE: usize = 256;

/// PLACEHOLDER (harness): the largest radius a broadphase query asks for, in
/// **voxels**. S2's combat phase replaces it with a weapon's range out of the
/// rules table (owner, at S2).
///
/// In voxels because a query radius in cells would make the answer's membership
/// depend on the cell edge, which the rules table declares a non-hashed tuning
/// knob — see [`Csr::collect_in_radius`]. Item 67's sizing rule is the other
/// direction of the same relation: the cell edge is chosen at least the largest
/// query radius so a query touches at most 3 x 3 cells, and 16 voxels is the
/// cell edge `rules/rules.v1.json` currently carries.
pub const BROADPHASE_QUERY_RADIUS_VOXELS: Fx = Fx::from_voxels(16);

/// How to build a world.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct WorldConfig {
    /// The match seed.
    ///
    /// The sim is a pure function of this, the playbooks and the rules hash —
    /// and **the map seed is the match seed**, not a value derived from it.
    /// One number, stated once, so a save that carries the match seed carries
    /// the map with it and a scenario file that names a seed names the map
    /// (`scenarios/skeleton/expand-east.scenario.jsonc`). A derived map seed
    /// would be a second number to keep in step for no gain: the map generator
    /// already draws on its own [`Stream::Map`], which is what keeps its draws
    /// from interleaving with anybody else's (item 50).
    pub match_seed: u64,
    /// How many seats share the match. At most three in v1; the determinism
    /// harness runs more because a wider table is a wider hash. Seat `i`
    /// occupies spawn zone `i`; a seat beyond the map's zones is seated but
    /// unplaced (see [`crate::mapgen`]).
    pub seats: u32,
    /// PLACEHOLDER (harness): how many extra walking units each seat fields on
    /// top of its starting force, so that the hash chain covers a wide table
    /// before T11 and T14 fill one honestly. A real match passes zero. Deleted
    /// when T14 fabricates units for real (owner, at T14).
    pub units_per_seat: u32,
    /// The rules table, an **input** to the sim and never hashed state.
    pub rules: RulesTable,
    /// What the lobby decided: the per-round segment length list and the round
    /// limit (item 40). [`MatchSettings::default`] takes the rules table's
    /// ladder and the spec's round limit.
    pub match_settings: MatchSettings,
}

/// The authoritative world: the hashed tables, the derived indexes and the
/// tick loop.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct World {
    // --- hashed state, in declared encoding order ---
    match_seed: u64,
    tick: Tick,
    seats: SeatTable,
    units: UnitTable,
    beacons: BeaconTable,
    structures: StructureTable,
    wrecks: WreckTable,
    chunks: ChunkDigests,

    // --- hashed state, continued: the router (item 62's routes) ---
    router: Router,

    // --- hashed state, continued: the match (T10) ---
    /// The phase, the round, the ladder and the outcome. See
    /// [`crate::runner`]: every field of it decides what a tick does, so all of
    /// it is hashed, snapshotted and in the goldens.
    match_state: MatchState,

    // --- the voxels themselves: hashed only through `chunks` (item 66) ---
    voxels: VoxelStore,

    // --- inputs and derived state: never encoded, never hashed ---
    rules: RulesTable,
    broadphase: Csr,
    /// The HPA\* surface graph. Derived from the chunk store and the cost rows,
    /// rebuilt on a restore rather than carried in a snapshot.
    surface: Surface,
    /// The HPA\* decomposition. Derived, as above.
    clusters: Clusters,
    /// The search's buffers, reused across every query of every tick.
    scratch: Scratch,
    /// The repair's working sets, and the dirty-cluster list the voxel phase
    /// fills.
    repairer: Repairer,
    work: WorkCounter,
    /// What the last tick's repair did. Diagnostic; never hashed.
    repair_report: RepairReport,
    /// What the last tick's serving did. Diagnostic; never hashed.
    serve_report: ServeReport,
    /// Scratch for the arrived-unit list, so a tick's destination draws
    /// allocate nothing.
    arrivals: Vec<u32>,
    /// This tick's voxel edits, drained by [`Phase::Voxels`].
    edits: Vec<VoxelEdit>,
    /// Scratch for a crater's touched-chunk list, so an edit allocates nothing.
    touched: Vec<u32>,
    /// Scratch for broadphase queries, so a query allocates nothing.
    candidates: Vec<u32>,
    /// This tick's damage orders, drained by [`Phase::Combat`].
    damage: Vec<DamageOrder>,
    /// What the tick reported. **Derived output, never hashed** — see
    /// [`crate::events`].
    events: EventBus,
    /// Each seat's commander, by unit index, or [`UnitId::NONE`] for a seat
    /// with none. Derived from the unit table, whose count is fixed at
    /// construction, so it is built once and rebuilt on a restore.
    commanders: Vec<u32>,
    /// Which beacons were alive at the end of the previous tick.
    ///
    /// Derived, never hashed: it exists to spot the *edge* — the tick a beacon
    /// died — so that item 20's local elimination and its event fire once
    /// rather than every tick afterwards. A restore rebuilds it from the
    /// restored hit points, which loses no edge, because a snapshot is taken
    /// after the match phase has already acted on this tick's deaths.
    beacon_alive: Vec<bool>,
}

/// What a damage order hits.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub enum DamageTarget {
    /// One unit.
    Unit(UnitId),
    /// One beacon.
    Beacon(BeaconId),
    /// One structure.
    Structure(StructureId),
}

/// One helping of damage, filed for this tick's combat phase.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct DamageOrder {
    /// What it hits.
    pub target: DamageTarget,
    /// How much, clamped at zero hit points by [`Hp::damaged_by`].
    pub amount: Hp,
}

/// Every hashed table of a restored world, handed over in one piece.
///
/// One struct rather than nine arguments because a restore that applies eight
/// of nine tables is not a state this sim has, and a positional argument list
/// nine long is how that happens.
#[derive(Clone, PartialEq, Eq, Debug)]
pub(crate) struct RestoredTables {
    pub(crate) match_seed: u64,
    pub(crate) tick: Tick,
    pub(crate) seats: SeatTable,
    pub(crate) units: UnitTable,
    pub(crate) beacons: BeaconTable,
    pub(crate) structures: StructureTable,
    pub(crate) wrecks: WreckTable,
    pub(crate) voxels: VoxelStore,
    pub(crate) chunks: ChunkDigests,
    pub(crate) router: crate::pathing::router::RestoredRouter,
    pub(crate) match_state: MatchState,
}

impl World {
    /// Generate the map for `config.match_seed` and build the world on it.
    ///
    /// The generator places each occupied seat's core beacon, commander and
    /// starting drones; the harness's `units_per_seat` extra walkers are
    /// appended after them, so unit ids stay dense and in seat order.
    ///
    /// # Errors
    ///
    /// Returns the [`MapError`] the generator reported, or
    /// [`MapError::Unindexable`] when the rules table cannot describe a
    /// broadphase grid for the resulting unit count — both of which are
    /// rules-table mistakes caught once, here, rather than every tick.
    pub fn new(config: &WorldConfig) -> Result<World, MapError> {
        let generated = mapgen::generate(config.match_seed, &config.rules, config.seats)?;
        let extent = config.rules.map_size_voxels();
        let max_x = i16::try_from(extent.first().copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);
        let max_y = i16::try_from(extent.get(1).copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);

        let harness_units = config.seats.saturating_mul(config.units_per_seat);
        let starting = u32::try_from(generated.starting_units.len()).unwrap_or(u32::MAX);
        let unit_count = starting.saturating_add(harness_units);

        let mut seats = SeatTable::with_capacity(config.seats);
        let mut seat_index: u32 = 0;
        while seat_index < config.seats {
            let at = usize::try_from(seat_index).unwrap_or(usize::MAX);
            seats.push(
                SeatId::new(u8::try_from(seat_index).unwrap_or(u8::MAX)),
                generated
                    .seat_treasury
                    .get(at)
                    .copied()
                    .unwrap_or(Money::ZERO),
                generated.seat_supply.get(at).copied().unwrap_or(Kw::ZERO),
                generated.seat_draw.get(at).copied().unwrap_or(Kw::ZERO),
            );
            seat_index = seat_index.saturating_add(1);
        }

        let units = fill_unit_table(config, &generated, unit_count, [max_x, max_y]);

        let mut voxels = generated.voxels;
        let chunk_total = voxels.chunk_count();
        let mut chunks = ChunkDigests::new(chunk_total);
        voxels.settle_all(&mut chunks);

        let Some(broadphase) = Csr::new(
            [0, 0],
            [
                extent.first().copied().unwrap_or(0),
                extent.get(1).copied().unwrap_or(0),
            ],
            config.rules.csr_cell_size_voxels(),
            unit_count,
        ) else {
            return Err(MapError::Unindexable { units: unit_count });
        };

        let cluster_voxels = config.rules.hpa_cluster_voxels();
        let Some(surface) = Surface::new(&voxels, StepCosts::from_rules(&config.rules)) else {
            return Err(MapError::BadExtent {
                size: voxels.size(),
            });
        };
        let Some((clusters, scratch)) = build_graph(&surface, cluster_voxels) else {
            return Err(MapError::Unclusterable { cluster_voxels });
        };
        let mut router = Router::new(unit_count, &config.rules);
        let mut unit = 0;
        while unit < unit_count {
            // Every unit starts by asking for a route: the harness's walkers
            // have a destination drawn on the map, and a starting unit's
            // destination is where it already stands, which the router answers
            // with "arrived" and the tick answers with a fresh destination.
            router.request(unit);
            unit = unit.saturating_add(1);
        }

        let beacons = generated.beacons;
        let beacon_alive = beacons
            .hit_points()
            .iter()
            .map(|hp| hp.is_alive())
            .collect();
        let commanders = commander_index(&units, config.seats);

        Ok(World {
            match_seed: config.match_seed,
            tick: Tick::ZERO,
            seats,
            units,
            beacons,
            structures: StructureTable::with_capacity(0),
            wrecks: WreckTable::with_capacity(0),
            chunks,
            router,
            match_state: MatchState::new(&config.match_settings, &config.rules),
            voxels,
            rules: config.rules.clone(),
            broadphase,
            repairer: Repairer::new(clusters.cluster_count()),
            surface,
            clusters,
            scratch,
            work: WorkCounter::with_budget(HARNESS_WORK_BUDGET),
            repair_report: RepairReport::default(),
            serve_report: ServeReport::default(),
            arrivals: Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0)),
            edits: Vec::with_capacity(HARNESS_EDIT_QUEUE),
            // Sized to the whole map rather than to the queue: one crater can
            // touch more chunks than the queue holds edits, and a scratch
            // buffer that has to grow is an allocation inside a tick.
            touched: Vec::with_capacity(usize::try_from(chunk_total).unwrap_or(0)),
            candidates: Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0)),
            damage: Vec::with_capacity(HARNESS_DAMAGE_QUEUE),
            events: EventBus::with_capacity(EVENT_BUS_CAPACITY),
            commanders,
            beacon_alive,
        })
    }

    /// The match seed, which is also the map seed ([`WorldConfig::match_seed`]).
    #[must_use]
    pub const fn match_seed(&self) -> u64 {
        self.match_seed
    }

    /// The current tick.
    #[must_use]
    pub const fn tick(&self) -> Tick {
        self.tick
    }

    /// The seat table.
    #[must_use]
    pub const fn seats(&self) -> &SeatTable {
        &self.seats
    }

    /// The unit table.
    #[must_use]
    pub const fn units(&self) -> &UnitTable {
        &self.units
    }

    /// The beacon table.
    #[must_use]
    pub const fn beacons(&self) -> &BeaconTable {
        &self.beacons
    }

    /// The structure table.
    #[must_use]
    pub const fn structures(&self) -> &StructureTable {
        &self.structures
    }

    /// The wreck table.
    #[must_use]
    pub const fn wrecks(&self) -> &WreckTable {
        &self.wrecks
    }

    /// The chunk store's digests.
    #[must_use]
    pub const fn chunks(&self) -> &ChunkDigests {
        &self.chunks
    }

    /// The chunk store's digests, for a test to perturb.
    ///
    /// The voxel phase refreshes these through [`VoxelStore::settle`]; nothing
    /// in the tick reaches for this.
    pub const fn chunks_mut(&mut self) -> &mut ChunkDigests {
        &mut self.chunks
    }

    /// The voxels.
    ///
    /// Read-only by design: the way to change a voxel is
    /// [`World::request_voxel_edit`], so every write lands in the voxel phase
    /// and every digest is refreshed in one place.
    #[must_use]
    pub const fn voxels(&self) -> &VoxelStore {
        &self.voxels
    }

    /// The rules table this world runs under. An input, never hashed state.
    #[must_use]
    pub const fn rules(&self) -> &RulesTable {
        &self.rules
    }

    /// The broadphase index. Derived, never hashed.
    #[must_use]
    pub const fn broadphase(&self) -> &Csr {
        &self.broadphase
    }

    /// The pathing graph's surface. Derived from the chunk store.
    #[must_use]
    pub const fn surface(&self) -> &Surface {
        &self.surface
    }

    /// The HPA\* decomposition. Derived from the surface.
    #[must_use]
    pub const fn clusters(&self) -> &Clusters {
        &self.clusters
    }

    /// The router: routes, walk states and the repath queue.
    #[must_use]
    pub const fn router(&self) -> &Router {
        &self.router
    }

    /// The search scratch, so a caller outside the tick — the gateway asking
    /// for an estimate, a test, a bench — can run a query without allocating a
    /// second set of dense arrays.
    ///
    /// Nothing in it is state: a query leaves the scratch different and the
    /// world identical, which `a_query_leaves_the_graph_alone` asserts.
    pub const fn scratch_mut(&mut self) -> &mut Scratch {
        &mut self.scratch
    }

    /// What the last tick's graph repair did.
    #[must_use]
    pub const fn repair_report(&self) -> RepairReport {
        self.repair_report
    }

    /// What the last tick's repath serving did.
    #[must_use]
    pub const fn serve_report(&self) -> ServeReport {
        self.serve_report
    }

    /// How many units are waiting for a repath right now.
    #[must_use]
    pub fn repath_backlog(&self) -> u32 {
        self.router.backlog()
    }

    /// The match's phase, round, ladder and outcome (T10).
    #[must_use]
    pub const fn match_state(&self) -> &MatchState {
        &self.match_state
    }

    /// Everything the tick reported since the last drain, in `(tick, seq)`
    /// order. Derived output, never hashed — see [`crate::events`].
    #[must_use]
    pub fn events(&self) -> &[Event] {
        self.events.as_slice()
    }

    /// The event bus itself, for the counts a host watches
    /// ([`EventBus::dropped`]).
    #[must_use]
    pub const fn event_bus(&self) -> &EventBus {
        &self.events
    }

    /// Take the reported events out, keeping the allocation.
    pub fn clear_events(&mut self) {
        self.events.clear();
    }

    /// Which unit is `seat`'s commander, or [`UnitId::NONE`].
    ///
    /// A seat beyond the map's occupied zones is seated but unplaced and has
    /// none (see [`crate::mapgen`]).
    #[must_use]
    pub fn commander_of(&self, seat: SeatId) -> UnitId {
        let index = usize::from(seat.raw());
        self.commanders
            .get(index)
            .copied()
            .map_or(UnitId::NONE, UnitId::new)
    }

    /// How many units are parked as sealed in right now.
    ///
    /// The standing count; the *edge* — a unit parking this tick — rides the
    /// event bus as `unit_sealed_in`, which is the report half of item 60's
    /// "park and report" (the PLACEHOLDER T7 left here named this task).
    #[must_use]
    pub fn sealed_units(&self) -> u32 {
        let mut count: u32 = 0;
        let mut unit: u32 = 0;
        while unit < self.router.len() {
            if self.router.state(unit) == WalkState::Sealed {
                count = count.saturating_add(1);
            }
            unit = unit.saturating_add(1);
        }
        count
    }

    /// This tick's work counter. Not hashed today; see [`WorkCounter`].
    #[must_use]
    pub const fn work(&self) -> WorkCounter {
        self.work
    }

    /// This tick's work counter, to charge against.
    ///
    /// Nothing in the tick charges it yet — the phases that will are T11's and
    /// S5's. It is reachable now so that
    /// `tests/determinism.rs`'s `the_work_counter_is_not_in_the_state_encoding`
    /// can prove the counter stays out of the hash.
    pub const fn work_mut(&mut self) -> &mut WorkCounter {
        &mut self.work
    }

    /// Ask for a voxel edit. Returns `false` when this tick's queue is full.
    ///
    /// **The order a filler owes.** The queue is applied in the order it was
    /// filled, so a phase that fills it must do so in an order that is itself
    /// deterministic — every sort key ending in a unique id, as everywhere else
    /// (item 62). Nothing fills it yet: combat's craters are S2's and
    /// construction's sets are T14's, and each of those phases already walks its
    /// own table in id order, which is the order the queue will inherit.
    ///
    /// A full queue drops nothing silently: the `false` is the report, and a
    /// caller that cannot afford to lose an edit must handle it.
    pub fn request_voxel_edit(&mut self, edit: VoxelEdit) -> bool {
        if self.edits.len() >= HARNESS_EDIT_QUEUE {
            return false;
        }
        self.edits.push(edit);
        true
    }

    /// How many edits are queued for this tick's voxel phase.
    #[must_use]
    pub fn queued_voxel_edits(&self) -> usize {
        self.edits.len()
    }

    /// File a damage order for this tick's combat phase. `false` when the
    /// queue is full.
    ///
    /// **What is T10's here and what is S2's.** The *source* of damage — who
    /// fires, at what, for how much, with what spread off `Stream::Combat` —
    /// is S2's and none of it exists. What exists is the drain: elimination,
    /// local elimination and the commander's respawn are all consequences of
    /// something dying, so T10 needs death to be a thing that can happen
    /// before it can implement the rules that follow from it. S2 fills the
    /// phase that files these orders; it does not have to change the way they
    /// land.
    ///
    /// The queue is applied in the order it was filled, so a filler owes the
    /// same discipline the voxel queue's does: fill it in an order that is
    /// itself deterministic, every sort key ending in a unique id (item 62).
    pub fn request_damage(&mut self, order: DamageOrder) -> bool {
        if self.damage.len() >= HARNESS_DAMAGE_QUEUE {
            return false;
        }
        self.damage.push(order);
        true
    }

    /// How many damage orders are queued for this tick's combat phase.
    #[must_use]
    pub fn queued_damage(&self) -> usize {
        self.damage.len()
    }

    /// Emit one event. Crate-internal: the phases and the runner are the only
    /// emitters.
    pub(crate) fn emit(&mut self, tick: Tick, emission: Emission) -> bool {
        self.events.emit(tick, emission)
    }

    /// Open a Push at `tick`, resetting the per-Push state item 21 makes
    /// per-Push. Crate-internal: [`crate::runner::Runner::begin_push`] is the
    /// only caller, so the phase machine cannot be walked around.
    pub(crate) fn open_push(&mut self, tick: Tick) {
        self.match_state.open_push(tick);
        let columns = self.seats.match_columns();
        for slot in columns.commander_deaths.iter_mut() {
            *slot = 0;
        }
        for slot in columns.respawn_due.iter_mut() {
            *slot = NO_RESPAWN;
        }
    }

    /// Close the recap at `tick`. `false` when that ended the match.
    /// Crate-internal for the same reason [`World::open_push`] is.
    pub(crate) fn close_recap(&mut self, tick: Tick) -> bool {
        self.match_state.close_recap(tick)
    }

    /// Advance one tick and return the tick's state hash.
    ///
    /// `enc` is the caller's buffer, reused across ticks: that is what makes a
    /// tick allocation-free (G3' section 9.17), and `tests/allocations.rs`
    /// asserts it.
    pub fn step(&mut self, enc: &mut Enc) -> u64 {
        self.tick = self.tick.next().unwrap_or(self.tick);
        self.work.reset();
        let mut hash = 0;
        for phase in PHASE_ORDER {
            match phase {
                Phase::Broadphase => self.phase_broadphase(),
                Phase::Programs => self.phase_programs(),
                Phase::Movement => self.phase_movement(),
                Phase::Combat => self.phase_combat(),
                Phase::KillCredit => self.phase_kill_credit(),
                Phase::Power => self.phase_power(),
                Phase::Quartermaster => self.phase_quartermaster(),
                Phase::Decision => self.phase_decision(),
                Phase::Pathing => self.phase_pathing(),
                Phase::Voxels => self.phase_voxels(),
                Phase::Match => self.phase_match(),
                Phase::Hash => hash = self.phase_hash(enc),
            }
        }
        hash
    }

    /// Rebuild the CSR uniform grid by counting sort (item 67).
    ///
    /// [`Csr::rebuild`] answers `false` when the unit table is larger than the
    /// grid it was built for, and leaves the grid **empty** — so swallowing
    /// that answer buys a world that hashes correctly and then queries an empty
    /// index for the rest of the match. [`World::new`] and
    /// [`World::restore_tables`] are the only two ways to get a grid, and both
    /// size it to the unit table, so a `false` here is a construction bug and
    /// the assertion is how it surfaces at the tick that caused it.
    fn phase_broadphase(&mut self) {
        let rebuilt = self.broadphase.rebuild(self.units.positions());
        debug_assert!(
            rebuilt,
            "the unit table outgrew the broadphase grid; every query from here on would come \
             back empty"
        );
    }

    /// Units' and buildings' built-in programs. **Empty: T14 fills it** (move,
    /// build, mine and scout).
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_programs(&mut self) {}

    /// Advance every mover along the route it is following.
    ///
    /// Item 90's accumulator, in one sentence: a walker adds its kind's
    /// `cost_per_second` to an integer accumulator each tick and spends one
    /// cost unit per 20 accumulated, so it arrives on
    /// `ceil(cost * 20 / cost_per_second)` — the tick the estimator promised.
    /// No float, no division that rounds a speed down, and no wandering: a unit
    /// walks the route [`Phase::Pathing`] gave it, one legal step at a time,
    /// and asks for another the moment a step stops being legal.
    ///
    /// What is *not* here is where a unit decides to go. The harness still
    /// draws a destination at random from [`Stream::Spawn`] when a unit arrives
    /// (see [`World::draw_new_destinations`]); T11's interpreter replaces that
    /// with the playbook, and the walking below does not change when it does.
    fn phase_movement(&mut self) {
        let MovementColumns {
            ids: _,
            seats: _,
            kinds,
            hit_points,
            positions,
            destinations: _,
            headings,
        } = self.units.movement_columns();
        self.router
            .advance(&self.surface, kinds, hit_points, positions, headings);
    }

    /// Fire and damage.
    ///
    /// **S2 fills the firing half**; `Stream::Combat` is reserved for it and is
    /// drawn from nowhere else. What is here is the landing half: this tick's
    /// [`DamageOrder`]s are applied in the order they were filed, and hit
    /// points clamp at zero because nothing is more destroyed than destroyed
    /// ([`Hp::damaged_by`]). T10 needs it because elimination, local
    /// elimination and the commander's respawn are consequences of a death, and
    /// a rule about a death cannot be written — or tested — against a world in
    /// which nothing can die.
    fn phase_combat(&mut self) {
        let orders = core::mem::take(&mut self.damage);
        for order in &orders {
            match order.target {
                DamageTarget::Unit(unit) => {
                    let index = usize::try_from(unit.raw()).unwrap_or(usize::MAX);
                    if let Some(slot) = self.units.hit_points_mut().get_mut(index) {
                        *slot = slot.damaged_by(order.amount);
                    }
                }
                DamageTarget::Beacon(beacon) => {
                    let index = usize::try_from(beacon.raw()).unwrap_or(usize::MAX);
                    if let Some(slot) = self.beacons.hit_points_mut().get_mut(index) {
                        *slot = slot.damaged_by(order.amount);
                    }
                }
                DamageTarget::Structure(structure) => {
                    let index = usize::try_from(structure.raw()).unwrap_or(usize::MAX);
                    if let Some(slot) = self.structures.hit_points_mut().get_mut(index) {
                        *slot = slot.damaged_by(order.amount);
                    }
                }
            }
        }
        self.damage = orders;
        self.damage.clear();
    }

    /// Per-seat kill-credit counters, at most three per asset, apportioned by
    /// largest remainder with ties to the lowest seat id. **Empty: T14 fills
    /// it**, and hashes the counters from the day they exist even though combat
    /// is S2 — a field that affects behaviour and is not hashed is a latent
    /// desync.
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_kill_credit(&mut self) {}

    /// Supply, draw, brownout order, dormancy, the revive margin. **Empty: T14
    /// fills it.**
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_power(&mut self) {}

    /// Hold fabricator orders, then the brownout order; fill spend requests by
    /// the urgency ladder, round-robin within a band. **Empty: T14 fills it**,
    /// behind the `Quartermaster` trait that is also T14's.
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T14 fills the body"
    )]
    const fn phase_quartermaster(&mut self) {}

    /// The interpreter's decision tick, one per 250 ms of game time. **Empty:
    /// T11 fills it.**
    #[allow(
        clippy::unused_self,
        reason = "an empty phase stub keeps the tick's shape visible; T11 fills the body"
    )]
    const fn phase_decision(&mut self) {}

    /// Repair the abstract graph, re-arm the units it may have freed, and serve
    /// the repath cap round-robin by `(seat, beacon, unit)`.
    ///
    /// The order is item 60's, and it is the reason a route is never planned
    /// over terrain that has moved: the repair runs **before** any repath this
    /// tick, and the columns the search reads were refreshed in the same tick
    /// the voxels changed (see [`World::phase_voxels`]). The one lag that does
    /// exist is a cluster's *entrances*, which are repaired here on the tick
    /// after the edit because [`PHASE_ORDER`] puts `Pathing` before `Voxels` —
    /// and that lag can only withhold routes, never invent one, because every
    /// step of a route is validated against the live columns as it is walked.
    fn phase_pathing(&mut self) {
        let report = repair(
            &self.surface,
            &mut self.clusters,
            &mut self.scratch,
            &mut self.repairer,
        );
        if report.dirty > 0 {
            self.router.rearm_sealed(
                &self.surface,
                &self.clusters,
                self.repairer.repaired(),
                self.units.positions(),
                self.units.destinations(),
            );
        }
        self.serve_report = self.router.serve(
            &self.surface,
            &self.clusters,
            &mut self.scratch,
            self.units.positions(),
            self.units.destinations(),
            self.rules.repath_cap_per_tick(),
        );
        self.repair_report = report;
        self.draw_new_destinations();
    }

    /// Give every unit that reached the end of a route somewhere new to be.
    ///
    /// PLACEHOLDER (harness): the destination is drawn from [`Stream::Spawn`] at
    /// `(tick, seat, unit id)`, which is the wandering T2 introduced so that the
    /// hash chain covers a moving table. T11's playbook interpreter is what
    /// replaces it with a destination somebody chose (owner, at T11).
    fn draw_new_destinations(&mut self) {
        if self.router.arrived().is_empty() {
            return;
        }
        self.arrivals.clear();
        self.arrivals.extend_from_slice(self.router.arrived());
        let match_seed = self.match_seed;
        let tick = self.tick.raw();
        let extent = self.rules.map_size_voxels();
        let max_x = i16::try_from(extent.first().copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);
        let max_y = i16::try_from(extent.get(1).copied().unwrap_or(0).saturating_sub(1))
            .unwrap_or(i16::MAX);
        let mut at = 0;
        while at < self.arrivals.len() {
            let Some(unit) = self.arrivals.get(at).copied() else {
                break;
            };
            at = at.saturating_add(1);
            let index = usize::try_from(unit).unwrap_or(usize::MAX);
            let seat = self.units.seats().get(index).copied().unwrap_or(0);
            let id = self.units.ids().get(index).copied().unwrap_or(0);
            let mut rng = StreamRng::new(match_seed, Stream::Spawn, tick, seat, id);
            let point = ground_point(&self.voxels, &mut rng, max_x, max_y);
            if let Some(slot) = self.units.destinations_mut().get_mut(index) {
                *slot = point;
            }
            self.router.request(unit);
        }
    }

    /// Apply this tick's voxel edits, then refresh the digest of every chunk
    /// they touched, in ascending chunk index.
    ///
    /// The queue is drained in the order it was filled (see
    /// [`World::request_voxel_edit`]); the *digests* are refreshed in chunk
    /// order regardless, because that is the order the canonical encoder walks
    /// them in and the only order the hash can see.
    ///
    /// The crater's touched-chunk list is written into the world's own scratch
    /// and then dropped: the phase does not need it, because
    /// [`VoxelStore::settle`] already walks every chunk any edit marked. It is
    /// passed rather than made optional so that the primitive has one signature,
    /// and it is a field rather than a local so that a crater inside a tick
    /// allocates nothing.
    fn phase_voxels(&mut self) {
        // The edit list and the touched scratch are separate fields from the
        // store, so draining one while writing the other borrows nothing twice.
        let edits = core::mem::take(&mut self.edits);
        let mut touched = core::mem::take(&mut self.touched);
        for edit in &edits {
            match *edit {
                VoxelEdit::Set { at, material } => {
                    self.voxels.set(at, material);
                }
                VoxelEdit::Crater { centre, radius } => {
                    self.voxels.crater(centre, radius, &mut touched);
                }
            }
        }
        self.voxels.settle(&mut self.chunks);
        // The pathing graph's columns are refreshed in the same phase that
        // changed the bytes, so a walker's next step is validated against the
        // terrain as it is; the *clusters* the edit dirtied are repaired at the
        // next tick's `Pathing` phase, which is where the entrance rescan and
        // the one connectivity rebuild live (item 60).
        let mut at = 0;
        while at < self.voxels.settled().len() {
            let Some(chunk) = self.voxels.settled().get(at).copied() else {
                break;
            };
            at = at.saturating_add(1);
            self.surface.refresh_chunk(&self.voxels, chunk);
            mark_chunk_clusters(&self.voxels, &self.clusters, &mut self.repairer, chunk);
        }
        touched.clear();
        self.touched = touched;
        self.edits = edits;
        self.edits.clear();
    }

    /// Settle the match (T10): the rules that follow from a tick's deaths, and
    /// the segment's end.
    ///
    /// The order below is the rule set's order, and each step is where it is
    /// because of the step before it:
    ///
    /// 1. **Report the units this tick sealed in.** Not a match rule — item
    ///    60's "park and report" — but the report half has to leave the sim
    ///    somewhere, and this is the phase that owns the event bus. It runs
    ///    outside the Push gate because it is true of a world stepped by hand
    ///    as well.
    /// 2. **Beacon deaths → local elimination** (item 20): the dead beacon's
    ///    structures become neutral ruins immediately.
    /// 3. **Seat elimination** (spec section 3): a seat whose last beacon has
    ///    fallen disbands its units on the spot and its structures become
    ///    ruins. Its commander despawns with them (item 21), which is why this
    ///    runs before anything that looks at a commander.
    /// 4. **Respawns that are due** (item 21).
    /// 5. **Commanders that died this tick** get their growing delay — after 4,
    ///    so that a commander coming back this tick cannot also be counted as
    ///    dying on it.
    /// 6. **The one-tick match-end rule** (item 16), evaluated every tick.
    /// 7. **The segment's end**, last, because a segment that ends must first
    ///    let this tick's deaths settle — and because a pending respawn
    ///    *always completes by segment end*, which is a force applied here.
    ///
    /// Outside a Push, only step 1 runs: `World::step` is the tick and runs
    /// whatever phase it is in, and a world nobody opened a Push on is not
    /// playing a segment (see [`crate::runner`]).
    fn phase_match(&mut self) {
        self.report_sealed_units();
        if self.match_state.phase() != MatchPhase::Push {
            return;
        }
        self.settle_beacon_deaths();
        self.settle_eliminations();
        self.settle_respawns(false);
        self.settle_commander_deaths();
        if self.check_match_end() {
            return;
        }
        self.close_segment_if_over();
    }

    /// Item 60's report half: one `unit_sealed_in` per unit this tick parked.
    fn report_sealed_units(&mut self) {
        if self.router.sealed_this_tick().is_empty() {
            return;
        }
        let tick = self.tick;
        let mut at: usize = 0;
        while at < self.router.sealed_this_tick().len() {
            let Some(unit) = self.router.sealed_this_tick().get(at).copied() else {
                break;
            };
            at = at.saturating_add(1);
            let index = usize::try_from(unit).unwrap_or(usize::MAX);
            let seat = self.units.seats().get(index).copied().unwrap_or(0);
            let position = self.units.positions().get(index).copied();
            let mut emission = Emission::of(EventKind::UnitSealedIn)
                .seat(SeatId::new(seat))
                .subject(AssetId::of_unit(UnitId::new(unit)));
            if let Some(point) = position {
                emission = emission.at(Position::from_array(point));
            }
            self.emit(tick, emission);
        }
    }

    /// Item 20: a beacon that reached zero hit points takes its structures with
    /// it, immediately, as neutral ruins.
    ///
    /// The edge is spotted against [`World::beacon_alive`], so this fires on
    /// the tick the beacon died and not on every tick after it.
    fn settle_beacon_deaths(&mut self) {
        let tick = self.tick;
        let count = usize::try_from(self.beacons.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < count {
            let alive = self
                .beacons
                .hit_points()
                .get(index)
                .is_some_and(|hp| hp.is_alive());
            let was_alive = self.beacon_alive.get(index).copied().unwrap_or(alive);
            if let Some(slot) = self.beacon_alive.get_mut(index) {
                *slot = alive;
            }
            if was_alive && !alive {
                let id = self.beacons.ids().get(index).copied().unwrap_or(0);
                let seat = self.beacons.seats().get(index).copied().unwrap_or(0);
                let at = self.beacons.positions().get(index).copied();
                let mut emission = Emission::of(EventKind::BeaconDestroyed)
                    .seat(SeatId::new(seat))
                    .subject(AssetId::of_beacon(BeaconId::new(id)));
                if let Some(point) = at {
                    emission = emission.at(Position::from_array(point));
                }
                self.emit(tick, emission);
                self.ruin_structures(Some(BeaconId::new(id)), None);
            }
            index = index.saturating_add(1);
        }
    }

    /// Turn structures into neutral ruins: those homed to `home`, or all of
    /// `seat`'s, whichever is given.
    ///
    /// Item 20's ruin, in one write: no owner. Inert, no supply, no draw, no
    /// capability, unrepairable, zero audit value — all of which follow from
    /// having no seat, rather than from five flags that could disagree.
    fn ruin_structures(&mut self, home: Option<BeaconId>, seat: Option<SeatId>) {
        let tick = self.tick;
        let count = usize::try_from(self.structures.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < count {
            let owner = self.structures.seats().get(index).copied().unwrap_or(0);
            let matches_home = home
                .is_some_and(|id| self.structures.homes().get(index).copied() == Some(id.raw()));
            let matches_seat = seat.is_some_and(|id| owner == id.raw());
            if SeatId::new(owner).is_some() && (matches_home || matches_seat) {
                let id = self.structures.ids().get(index).copied().unwrap_or(0);
                let at = self.structures.positions().get(index).copied();
                if let Some(slot) = self.structures.seats_mut().get_mut(index) {
                    *slot = SeatId::NEUTRAL.raw();
                }
                let mut emission = Emission::of(EventKind::StructureRuined)
                    .subject(AssetId::of_structure(StructureId::new(id)));
                if let Some(point) = at {
                    emission = emission.at(Position::from_array(point));
                }
                self.emit(tick, emission);
            }
            index = index.saturating_add(1);
        }
    }

    /// Spec section 3: when a seat's last beacon falls, its units disband on
    /// the spot and its structures become neutral ruins.
    ///
    /// **A seat with no beacon row at all is not eliminated**, because it was
    /// never placed: the determinism harness runs four seats on a three-zone
    /// map on purpose, and a seat beyond the map's zones is seated but unplaced
    /// (see [`crate::mapgen`]). It never had a core to lose, so it is neither
    /// eliminated nor counted by the one-tick rule. A seat's first beacon is
    /// its core (spec section 3), so "has a beacon row" is exactly "was in the
    /// match".
    fn settle_eliminations(&mut self) {
        let tick = self.tick;
        let seats = usize::try_from(self.seats.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < seats {
            let raw = self.seats.seats().get(index).copied().unwrap_or(0);
            let standing = self.seat_standing(raw);
            if self.seats.is_alive(index) && standing == SeatStanding::Fallen {
                {
                    let columns = self.seats.match_columns();
                    if let Some(slot) = columns.eliminated_at.get_mut(index) {
                        *slot = tick.raw();
                    }
                    if let Some(slot) = columns.respawn_due.get_mut(index) {
                        *slot = NO_RESPAWN;
                    }
                }
                self.disband_units(SeatId::new(raw));
                self.ruin_structures(None, Some(SeatId::new(raw)));
                self.emit(
                    tick,
                    Emission::of(EventKind::SeatEliminated).seat(SeatId::new(raw)),
                );
            }
            index = index.saturating_add(1);
        }
    }

    /// Disband every one of a seat's units where it stands, the commander
    /// included (item 21: it despawns at the tick its seat is eliminated).
    ///
    /// A disbanded unit also loses its route: a route is a decision a unit made
    /// and a disbanded unit is making none, and leaving it in the repath queue
    /// would spend the tick's cap on the dead.
    fn disband_units(&mut self, seat: SeatId) {
        let count = usize::try_from(self.units.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < count {
            if self.units.seats().get(index).copied() == Some(seat.raw()) {
                if let Some(slot) = self.units.hit_points_mut().get_mut(index) {
                    *slot = Hp::ZERO;
                }
                if let Ok(unit) = u32::try_from(index) {
                    self.router.clear(unit);
                }
            }
            index = index.saturating_add(1);
        }
    }

    /// Item 21: bring back every commander whose respawn is due.
    ///
    /// `force` completes every pending respawn regardless of its due tick, and
    /// is what "a pending respawn always completes by segment end, so every
    /// Lull snapshot has a live commander at a known place" means in code.
    ///
    /// The place is the core — the seat's lowest-id beacon — or, if the core is
    /// gone, the surviving beacon nearest to where the commander died, ties to
    /// the lowest beacon id (item 62's convention). A seat with no living
    /// beacon at all is being eliminated in the same tick, so it has nowhere to
    /// come back to and does not.
    fn settle_respawns(&mut self, force: bool) {
        let tick = self.tick;
        let seats = usize::try_from(self.seats.len()).unwrap_or(0);
        let hp = self.commander_hp();
        let mut index: usize = 0;
        while index < seats {
            let due = self
                .seats
                .respawn_due()
                .get(index)
                .copied()
                .unwrap_or(NO_RESPAWN);
            let alive_seat = self.seats.is_alive(index);
            if due == NO_RESPAWN || !alive_seat || (!force && due > tick.raw()) {
                index = index.saturating_add(1);
                continue;
            }
            let raw = self.seats.seats().get(index).copied().unwrap_or(0);
            let commander = self.commander_of(SeatId::new(raw));
            let Some(unit) = usize::try_from(commander.raw())
                .ok()
                .filter(|_| commander.is_some())
            else {
                index = index.saturating_add(1);
                continue;
            };
            let died_at = self
                .units
                .positions()
                .get(unit)
                .copied()
                .unwrap_or([Fx::ZERO; 3]);
            let Some(point) = self.respawn_point(raw, died_at) else {
                index = index.saturating_add(1);
                continue;
            };
            if let Some(slot) = self.units.positions_mut().get_mut(unit) {
                *slot = point;
            }
            if let Some(slot) = self.units.hit_points_mut().get_mut(unit) {
                *slot = hp;
            }
            if let Some(slot) = self.units.destinations_mut().get_mut(unit) {
                *slot = point;
            }
            if let Ok(id) = u32::try_from(unit) {
                self.router.clear(id);
                self.router.request(id);
            }
            {
                let columns = self.seats.match_columns();
                if let Some(slot) = columns.respawn_due.get_mut(index) {
                    *slot = NO_RESPAWN;
                }
            }
            let waited = tick.raw().saturating_sub(due);
            self.emit(
                tick,
                Emission::of(EventKind::CommanderRespawned)
                    .seat(SeatId::new(raw))
                    .subject(AssetId::of_unit(commander))
                    .at(Position::from_array(point))
                    .value(i64::from(waited)),
            );
            index = index.saturating_add(1);
        }
    }

    /// Item 21: a commander that has reached zero hit points and has no
    /// respawn pending has just died. Book the death and its growing delay.
    ///
    /// The condition is the state itself rather than a remembered edge, which
    /// is what keeps it from firing twice: the write that books the death is
    /// the write that makes the condition false.
    fn settle_commander_deaths(&mut self) {
        let tick = self.tick;
        let (base, growth) = self.respawn_curve();
        let seats = usize::try_from(self.seats.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < seats {
            let raw = self.seats.seats().get(index).copied().unwrap_or(0);
            let commander = self.commander_of(SeatId::new(raw));
            let dead = usize::try_from(commander.raw())
                .ok()
                .filter(|_| commander.is_some())
                .and_then(|unit| self.units.hit_points().get(unit).copied())
                .is_some_and(|hp| !hp.is_alive());
            let pending = self
                .seats
                .respawn_due()
                .get(index)
                .copied()
                .unwrap_or(NO_RESPAWN)
                != NO_RESPAWN;
            if dead && !pending && self.seats.is_alive(index) {
                let deaths = self
                    .seats
                    .commander_deaths()
                    .get(index)
                    .copied()
                    .unwrap_or(0);
                let delay = Ms::new(
                    base.saturating_add(growth.saturating_mul(i32::try_from(deaths).unwrap_or(0))),
                );
                let due = tick.raw().saturating_add(delay.to_ticks_ceil());
                {
                    let columns = self.seats.match_columns();
                    if let Some(slot) = columns.commander_deaths.get_mut(index) {
                        *slot = deaths.saturating_add(1);
                    }
                    if let Some(slot) = columns.respawn_due.get_mut(index) {
                        *slot = due;
                    }
                }
                let at = usize::try_from(commander.raw())
                    .ok()
                    .and_then(|unit| self.units.positions().get(unit).copied());
                let mut emission = Emission::of(EventKind::CommanderDied)
                    .seat(SeatId::new(raw))
                    .subject(AssetId::of_unit(commander))
                    .value(i64::from(deaths.saturating_add(1)));
                if let Some(point) = at {
                    emission = emission.at(Position::from_array(point));
                }
                self.emit(tick, emission);
            }
            index = index.saturating_add(1);
        }
    }

    /// Item 16, the one-tick rule: end conditions are evaluated **every tick**,
    /// and the Push halts at the first tick where fewer than two seats remain.
    ///
    /// `true` when this tick ended the match. If no seat survives that tick the
    /// final audit at that tick decides, so the outcome is
    /// [`MatchEndReason::NoSurvivor`] with no winner — there is no draw state,
    /// and the audit that would name a winner is T14's.
    fn check_match_end(&mut self) -> bool {
        let mut remaining: u32 = 0;
        let mut last: Option<SeatId> = None;
        let seats = usize::try_from(self.seats.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < seats {
            let raw = self.seats.seats().get(index).copied().unwrap_or(0);
            if self.seats.is_alive(index) && self.seat_standing(raw) == SeatStanding::Standing {
                remaining = remaining.saturating_add(1);
                last = Some(SeatId::new(raw));
            }
            index = index.saturating_add(1);
        }
        if remaining >= 2 {
            return false;
        }
        // This is a segment end like any other, so item 21's rule holds
        // without an exception: a pending respawn always completes by segment
        // end. An eliminated seat's does not, because `settle_respawns` skips
        // a seat that is out.
        self.settle_respawns(true);
        let tick = self.tick;
        let ran = tick.since(self.match_state.segment_started());
        let (reason, winner) = match last {
            Some(seat) => (MatchEndReason::LastSeatStanding, Some(seat)),
            None => (MatchEndReason::NoSurvivor, None),
        };
        self.emit(
            tick,
            Emission::of(EventKind::SegmentEnded).value(i64::from(ran)),
        );
        self.match_state.decide(reason, winner, tick);
        let round = self.match_state.round();
        self.emit(
            tick,
            Emission::of(EventKind::RecapOpened).value(i64::from(round)),
        );
        let mut emission = Emission::of(EventKind::MatchEnded).value(i64::from(reason.id()));
        if let Some(seat) = winner {
            emission = emission.seat(seat);
        }
        self.emit(tick, emission);
        true
    }

    /// Close the segment once it has run its length, freeing every pending
    /// respawn on the way out.
    fn close_segment_if_over(&mut self) {
        let ticks = self.match_state.segment_ticks();
        let ran = self.tick.since(self.match_state.segment_started());
        if ran < ticks {
            return;
        }
        // Item 21, in one line: the respawn always completes by segment end,
        // so every Lull snapshot has a live commander at a known place.
        self.settle_respawns(true);
        let tick = self.tick;
        self.emit(
            tick,
            Emission::of(EventKind::SegmentEnded).value(i64::from(ran)),
        );
        self.match_state.close_segment(tick);
        let round = self.match_state.round();
        self.emit(
            tick,
            Emission::of(EventKind::RecapOpened).value(i64::from(round)),
        );
    }

    /// Whether a seat is standing, has fallen, or was never placed.
    fn seat_standing(&self, seat: u8) -> SeatStanding {
        let mut placed = false;
        let count = usize::try_from(self.beacons.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < count {
            if self.beacons.seats().get(index).copied() == Some(seat) {
                placed = true;
                if self
                    .beacons
                    .hit_points()
                    .get(index)
                    .is_some_and(|hp| hp.is_alive())
                {
                    return SeatStanding::Standing;
                }
            }
            index = index.saturating_add(1);
        }
        if placed {
            SeatStanding::Fallen
        } else {
            SeatStanding::Unplaced
        }
    }

    /// Where a seat's commander comes back: the core, or the surviving beacon
    /// nearest `from`, ties to the lowest beacon id.
    fn respawn_point(&self, seat: u8, from: [Fx; 3]) -> Option<[Fx; 3]> {
        let mut core: Option<(u32, [Fx; 3], bool)> = None;
        let mut nearest: Option<(Sq, u32, [Fx; 3])> = None;
        let count = usize::try_from(self.beacons.len()).unwrap_or(0);
        let mut index: usize = 0;
        while index < count {
            if self.beacons.seats().get(index).copied() == Some(seat) {
                let id = self.beacons.ids().get(index).copied().unwrap_or(0);
                let at = self
                    .beacons
                    .positions()
                    .get(index)
                    .copied()
                    .unwrap_or([Fx::ZERO; 3]);
                let alive = self
                    .beacons
                    .hit_points()
                    .get(index)
                    .is_some_and(|hp| hp.is_alive());
                if core.is_none_or(|(best, _, _)| id < best) {
                    core = Some((id, at, alive));
                }
                if alive {
                    let distance = Sq::between(at, from);
                    if nearest.is_none_or(|(best, best_id, _)| (distance, id) < (best, best_id)) {
                        nearest = Some((distance, id, at));
                    }
                }
            }
            index = index.saturating_add(1);
        }
        match core {
            Some((_, at, true)) => Some(at),
            _ => nearest.map(|(_, _, at)| at),
        }
    }

    /// The commander's hit points, from `commander.hp`.
    fn commander_hp(&self) -> Hp {
        self.rules
            .message()
            .commander
            .as_ref()
            .and_then(|block| i32::try_from(block.hp).ok())
            .map_or(Hp::ZERO, Hp::new)
    }

    /// The respawn delay curve: `commander.respawn_base_ms` plus
    /// `commander.respawn_growth_ms` per earlier death in the same Push
    /// (item 90's rows, both PLACEHOLDER tuning re-derived by the owner at S2).
    ///
    /// Read from the rules table and never from a constant (AGENTS.md §12),
    /// which is also what makes the curve a tuning question rather than a code
    /// change.
    fn respawn_curve(&self) -> (i32, i32) {
        self.rules
            .message()
            .commander
            .as_ref()
            .map_or((0, 0), |block| {
                (block.respawn_base_ms, block.respawn_growth_ms)
            })
    }

    /// Encode the world and digest it.
    fn phase_hash(&self, enc: &mut Enc) -> u64 {
        self.encode(enc);
        enc.finish()
    }

    /// Append the world to the canonical encoding, in **declared table order**.
    ///
    /// The order below is the contract. Adding a table means appending it here,
    /// adding it to the snapshot round-trip and re-blessing the goldens, all in
    /// the same pull request (AGENTS.md section 4.8).
    ///
    /// 1. header — match seed, tick
    /// 2. seats
    /// 3. units
    /// 4. beacons
    /// 5. structures
    /// 6. wrecks
    /// 7. chunk digests
    /// 8. the router — per unit: walk state, speed accumulator, route length,
    ///    route cursor, whether the route is partial, and the **route's
    ///    digest**; then the round-robin cursor. The route's nodes reach the
    ///    hash through that digest for the reason the chunk store's bytes reach
    ///    it through per-chunk digests (item 66): a column that grows with the
    ///    map does not belong in a per-tick encoding. The nodes themselves
    ///    travel in the snapshot, and a restore that produced a different route
    ///    shows up as a moved digest — which is a claim only because
    ///    [`crate::snapshot::Snapshot`] recomputes every carried digest from the
    ///    restored nodes and refuses the file with
    ///    [`crate::snapshot::SnapshotError::RouteDigest`] when the two
    ///    disagree, exactly as it does for the chunk store.
    /// 9. the match state — phase, round, round limit, the effective per-round
    ///    length list, the segment's start tick and length, the coming
    ///    segment's length and the outcome ([`crate::runner::MatchState`]).
    ///    Every one of those decides what a tick does, so every one is here.
    ///
    /// The seat block gained three columns with the match state: the tick a
    /// seat was eliminated at, its commander's death count for this Push, and
    /// the tick a pending respawn is due — hashed for the same reason.
    ///
    /// The rules table, the voxel bytes, the broadphase and the work counter
    /// are **not** here. The first, third and fourth are inputs or derived
    /// state, and `tests/determinism.rs` asserts that changing a performance
    /// knob leaves the chain byte-identical; the voxels reach the hash through
    /// their per-chunk digests and never as bytes (item 66).
    pub fn encode(&self, enc: &mut Enc) {
        enc.clear();
        enc.u64(self.match_seed);
        enc.u32(self.tick.raw());

        self.encode_seats(enc);

        enc.len(self.units.len());
        let positions = self.units.positions();
        let destinations = self.units.destinations();
        let headings = self.units.headings();
        let hit_points = self.units.hit_points();
        let kinds = self.units.kinds();
        for (index, id) in self.units.ids().iter().enumerate() {
            enc.u32(*id);
            enc.u8(self.units.seats().get(index).copied().unwrap_or(0));
            enc.u8(kinds.get(index).copied().unwrap_or(0));
            encode_point(enc, positions.get(index));
            encode_point(enc, destinations.get(index));
            enc.u16(headings.get(index).copied().unwrap_or(Angle::ZERO).raw());
            enc.i32(hit_points.get(index).copied().unwrap_or(Hp::ZERO).raw());
        }

        enc.len(self.beacons.len());
        let beacon_positions = self.beacons.positions();
        let mandates = self.beacons.mandates();
        let programs = self.beacons.programs();
        let beacon_hp = self.beacons.hit_points();
        let dormant = self.beacons.dormant();
        for (index, id) in self.beacons.ids().iter().enumerate() {
            enc.u32(*id);
            enc.u8(self.beacons.seats().get(index).copied().unwrap_or(0));
            encode_point(enc, beacon_positions.get(index));
            enc.u8(mandates.get(index).copied().unwrap_or(0));
            enc.u32(programs.get(index).copied().unwrap_or(0));
            enc.i32(beacon_hp.get(index).copied().unwrap_or(Hp::ZERO).raw());
            enc.bool(dormant.get(index).copied().unwrap_or(false));
        }

        enc.len(self.structures.len());
        let structure_positions = self.structures.positions();
        let structure_kinds = self.structures.kinds();
        let structure_hp = self.structures.hit_points();
        let homes = self.structures.homes();
        for (index, id) in self.structures.ids().iter().enumerate() {
            enc.u32(*id);
            enc.u8(self.structures.seats().get(index).copied().unwrap_or(0));
            enc.u8(structure_kinds.get(index).copied().unwrap_or(0));
            encode_point(enc, structure_positions.get(index));
            enc.i32(structure_hp.get(index).copied().unwrap_or(Hp::ZERO).raw());
            enc.u32(homes.get(index).copied().unwrap_or(u32::MAX));
        }

        enc.len(self.wrecks.len());
        let wreck_positions = self.wrecks.positions();
        let salvages = self.wrecks.salvages();
        for (index, id) in self.wrecks.ids().iter().enumerate() {
            enc.u32(*id);
            encode_point(enc, wreck_positions.get(index));
            enc.i64(salvages.get(index).copied().unwrap_or(Money::ZERO).raw());
        }

        self.chunks.encode(enc);
        self.router.encode(enc);
        self.match_state.encode(enc);
    }

    /// The seat block of the canonical encoding: treasury and power, then the
    /// three match columns T10 added.
    ///
    /// Split out of [`World::encode`] because the seat row is now seven fields
    /// wide and the encoder reads better as one block per table than as one
    /// function per world.
    fn encode_seats(&self, enc: &mut Enc) {
        enc.len(self.seats.len());
        for (index, seat) in self.seats.seats().iter().enumerate() {
            enc.u8(*seat);
            enc.i64(
                self.seats
                    .treasuries()
                    .get(index)
                    .copied()
                    .unwrap_or(Money::ZERO)
                    .raw(),
            );
            enc.i32(
                self.seats
                    .supplies()
                    .get(index)
                    .copied()
                    .unwrap_or(Kw::ZERO)
                    .raw(),
            );
            enc.i32(
                self.seats
                    .draws()
                    .get(index)
                    .copied()
                    .unwrap_or(Kw::ZERO)
                    .raw(),
            );
            enc.u32(
                self.seats
                    .eliminated_at()
                    .get(index)
                    .copied()
                    .unwrap_or(NOT_ELIMINATED),
            );
            enc.u32(
                self.seats
                    .commander_deaths()
                    .get(index)
                    .copied()
                    .unwrap_or(0),
            );
            enc.u32(
                self.seats
                    .respawn_due()
                    .get(index)
                    .copied()
                    .unwrap_or(NO_RESPAWN),
            );
        }
    }

    /// The per-tick state hash, allocating its own encoder.
    ///
    /// The tick loop uses [`World::step`]'s reused buffer instead; this form is
    /// for tests, snapshots and one-off checks.
    #[must_use]
    pub fn state_hash(&self) -> u64 {
        let mut enc = Enc::with_capacity(16 * 1024);
        self.encode(&mut enc);
        enc.finish()
    }

    /// The ids within `radius` **voxels** of `centre`, sorted ascending, in the
    /// world's own scratch buffer.
    ///
    /// Allocation-free after construction, and independent of the broadphase's
    /// cell size in both membership and order — see
    /// [`Csr::collect_in_radius`], which does the exact range test the grid
    /// itself cannot.
    pub fn candidates_near(&mut self, centre: [Fx; 3], radius: Fx) -> &[u32] {
        let mut scratch = core::mem::take(&mut self.candidates);
        self.broadphase
            .collect_in_radius(self.units.positions(), centre, radius, &mut scratch);
        self.candidates = scratch;
        &self.candidates
    }

    /// Replace the hashed tables from a restored snapshot, and **resize the
    /// derived index to match them**.
    ///
    /// The broadphase is sized for a unit count at construction. A snapshot
    /// holding more units than the receiving world was built for would
    /// otherwise restore cleanly, hash correctly, and leave every later
    /// broadphase query empty — see [`World::phase_broadphase`]. So the grid is
    /// rebuilt here, for the restored count, before anything is written.
    ///
    /// Returns `false` and changes **nothing** when the grid cannot be built
    /// for the restored world, the same answer [`World::new`] gives for the
    /// same reason. A half-applied restore is not a state this sim has.
    ///
    /// Crate-internal: [`crate::snapshot`] is the only caller, so a restore
    /// cannot skip the version check.
    pub(crate) fn restore_tables(&mut self, restored: RestoredTables) -> bool {
        let unit_count = restored.units.len();
        let extent = self.rules.map_size_voxels();
        let Some(broadphase) = Csr::new(
            [0, 0],
            [
                extent.first().copied().unwrap_or(0),
                extent.get(1).copied().unwrap_or(0),
            ],
            self.rules.csr_cell_size_voxels(),
            unit_count,
        ) else {
            return false;
        };
        // The router is restored before anything is written, for the same
        // reason the grid is built first: a file whose route columns disagree
        // must leave the world exactly as it was.
        if !self.router.restore(restored.router) {
            return false;
        }

        self.match_seed = restored.match_seed;
        self.tick = restored.tick;
        self.seats = restored.seats;
        self.units = restored.units;
        self.commanders = commander_index(&self.units, self.seats.len());
        self.beacons = restored.beacons;
        self.beacon_alive = self
            .beacons
            .hit_points()
            .iter()
            .map(|hp| hp.is_alive())
            .collect();
        self.match_state.restore(restored.match_state);
        self.structures = restored.structures;
        self.wrecks = restored.wrecks;
        self.voxels = restored.voxels;
        self.chunks = restored.chunks;
        self.broadphase = broadphase;
        // The pathing graph is derived, so it is rebuilt from the restored
        // store rather than carried in the file — and `tests/pathing.rs`'s
        // `a_restored_world_rebuilds_the_graph_it_was_saved_with` is what makes
        // "derived" a checked claim rather than a convenient one.
        self.surface.refresh_all(&self.voxels);
        self.clusters.rebuild_all(&self.surface, &mut self.scratch);
        self.repairer = Repairer::new(self.clusters.cluster_count());
        self.arrivals = Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0));
        self.repair_report = RepairReport::default();
        self.serve_report = ServeReport::default();
        self.edits.clear();
        self.damage.clear();
        // The event bus is derived output and is not in the file
        // ([`crate::events`]): a restored world starts with an empty feed,
        // which costs nothing because a host drains it every tick and a save is
        // written at a segment boundary, with the bus already empty.
        self.events.clear();
        self.touched = Vec::with_capacity(usize::try_from(self.voxels.chunk_count()).unwrap_or(0));
        // The query scratch is sized the same way, and for the same reason: a
        // query that has to grow its buffer is an allocation inside a tick.
        self.candidates = Vec::with_capacity(usize::try_from(unit_count).unwrap_or(0));
        true
    }
}

/// Where a seat stands in the match.
///
/// Three states rather than two, because "has no living beacon" is two
/// different things: a seat whose core has fallen is **out**, and a seat that
/// was never placed was never **in**. See [`World::settle_eliminations`].
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
enum SeatStanding {
    /// At least one beacon of this seat is alive.
    Standing,
    /// This seat had beacons and none of them is alive.
    Fallen,
    /// This seat has no beacon row at all: it was seated but never placed.
    Unplaced,
}

/// Each seat's commander, by unit index, or [`UnitId::NONE`].
///
/// Derived from the unit table, which fixes its count at construction, so it is
/// built once here and rebuilt on a restore. The **first** commander row a seat
/// has, in unit-id order, which is the only commander a seat ever has (spec
/// section 4: one per occupied seat).
fn commander_index(units: &UnitTable, seats: u32) -> Vec<u32> {
    let mut commanders = vec![UnitId::NONE.raw(); usize::try_from(seats).unwrap_or(0)];
    let commander = UnitKind::Commander.id();
    for (index, kind) in units.kinds().iter().enumerate() {
        if *kind != commander {
            continue;
        }
        let Some(seat) = units.seats().get(index).copied() else {
            continue;
        };
        let Ok(id) = u32::try_from(index) else {
            continue;
        };
        if let Some(slot) = commanders.get_mut(usize::from(seat))
            && *slot == UnitId::NONE.raw()
        {
            *slot = id;
        }
    }
    commanders
}

/// The unit table: the generator's starting force first, then the harness's
/// extra walkers, seat by seat.
///
/// One pass, in that order, so unit ids stay **dense and in seat order** —
/// which is what lets [`Csr`] use a row index as an id and what makes every
/// sort key that ends in a unit id a total order (item 62).
fn fill_unit_table(
    config: &WorldConfig,
    generated: &crate::mapgen::GeneratedMap,
    capacity: u32,
    extent: [i16; 2],
) -> UnitTable {
    let mut units = UnitTable::with_capacity(capacity);
    let mut next_id: u32 = 0;
    for unit in &generated.starting_units {
        // A starting unit begins where it stands: the harness walk gives it a
        // destination the moment it notices it has arrived.
        units.push(
            UnitId::new(next_id),
            unit.seat,
            unit.kind,
            unit.at,
            unit.at,
            unit.hp,
        );
        next_id = next_id.saturating_add(1);
    }

    // PLACEHOLDER (harness): the extra walkers are raiders because a raider is
    // the cheapest kind with a rules-table HP row that is not part of a seat's
    // starting force, so they cannot be mistaken for one. T14 deletes them
    // along with `WorldConfig::units_per_seat`.
    let walker_hp = config
        .rules
        .unit_hp(UnitKind::Raider)
        .unwrap_or(Hp::new(100));
    let max_x = extent.first().copied().unwrap_or(0);
    let max_y = extent.get(1).copied().unwrap_or(0);
    let mut seat_index: u32 = 0;
    while seat_index < config.seats {
        let seat = SeatId::new(u8::try_from(seat_index).unwrap_or(u8::MAX));
        let mut n: u32 = 0;
        while n < config.units_per_seat {
            let mut rng = StreamRng::new(
                config.match_seed,
                Stream::Spawn,
                Tick::ZERO.raw(),
                seat.raw(),
                next_id,
            );
            let pos = ground_point(&generated.voxels, &mut rng, max_x, max_y);
            let dest = ground_point(&generated.voxels, &mut rng, max_x, max_y);
            units.push(
                UnitId::new(next_id),
                seat,
                UnitKind::Raider,
                pos,
                dest,
                walker_hp,
            );
            next_id = next_id.saturating_add(1);
            n = n.saturating_add(1);
        }
        seat_index = seat_index.saturating_add(1);
    }
    units
}

/// Build the pathing graph and the scratch it is searched with.
///
/// The scratch has to be sized before the decomposition exists — building the
/// intra edges is itself a search — so [`Scratch::for_map`] does that
/// arithmetic from the map and the cluster edge, and the decomposition is
/// checked against it below.
///
/// `None` when the cluster edge cannot decompose this map, which the caller
/// reports as [`MapError::Unclusterable`].
fn build_graph(surface: &Surface, cluster_voxels: i32) -> Option<(Clusters, Scratch)> {
    let mut scratch = Scratch::for_map(surface, cluster_voxels)?;
    let clusters = Clusters::new(surface, cluster_voxels, &mut scratch)?;
    // A real check rather than a `debug_assert!`: this is the only thing tying
    // the scratch's independent derivation of the abstract numbering to the
    // decomposition's, and a release build is exactly where a scratch sized for
    // a different numbering would go unnoticed — the arrays would be short and
    // a query would read a slot that is not there.
    if clusters.abstract_capacity() != Scratch::abstract_capacity_for(surface, cluster_voxels)? {
        return None;
    }
    Some((clusters, scratch))
}

/// Mark every cluster a settled chunk's footprint overlaps.
///
/// At the decided cluster edge of 32 a chunk footprint *is* a cluster (item 58),
/// and this loop is one iteration. It is written as a loop anyway because the
/// cluster edge is a rules-table row and the cluster-size sweep in
/// `tests/pathing.rs` runs the decomposition at 16 and 64, where a chunk covers
/// four clusters or a quarter of one.
fn mark_chunk_clusters(
    voxels: &VoxelStore,
    clusters: &Clusters,
    repairer: &mut Repairer,
    chunk: u32,
) {
    let Some(origin) = voxels.chunk_origin(chunk) else {
        return;
    };
    let edge = i32::try_from(CHUNK_EDGE).unwrap_or(32);
    let size = clusters.size().max(1);
    let x0 = origin.first().copied().unwrap_or(0);
    let y0 = origin.get(1).copied().unwrap_or(0);
    let mut cy = y0.div_euclid(size);
    while cy <= y0.saturating_add(edge.saturating_sub(1)).div_euclid(size) {
        let mut cx = x0.div_euclid(size);
        while cx <= x0.saturating_add(edge.saturating_sub(1)).div_euclid(size) {
            if let Some(cluster) = clusters.cluster_index(cx, cy)
                && let Ok(tag) = u16::try_from(cluster)
            {
                repairer.mark(tag);
            }
            cx = cx.saturating_add(1);
        }
        cy = cy.saturating_add(1);
    }
}

fn encode_point(enc: &mut Enc, point: Option<&[Fx; 3]>) {
    let p = point.copied().unwrap_or([Fx::ZERO; 3]);
    for axis in p {
        enc.i32(axis.raw());
    }
}

/// A point drawn uniformly over the map footprint, standing on the surface of
/// whatever column it landed in.
fn ground_point(voxels: &VoxelStore, rng: &mut StreamRng, max_x: i16, max_y: i16) -> [Fx; 3] {
    let x = rng.range_i32(0, i32::from(max_x));
    let y = rng.range_i32(0, i32::from(max_y));
    let z = voxels.standing_z(x, y);
    [
        Fx::from_voxels(i16::try_from(x).unwrap_or(0)),
        Fx::from_voxels(i16::try_from(y).unwrap_or(0)),
        Fx::from_voxels(i16::try_from(z).unwrap_or(0)),
    ]
}
