// SPDX-FileCopyrightText: 2026 Pharmakos contributors
// SPDX-License-Identifier: GPL-3.0-or-later

//! Step 2 of the measurement procedure: verify the hash function itself before
//! trusting it, and pin the fixed-point edge cases.
//!
//! An XXH3 implementation that disagrees with the published reference vectors is
//! a project-ending trap, and it is discovered cheaply here. The vectors below
//! come from upstream xxHash's `xsum_sanity_check.c`, whose test buffer is
//! generated by a documented integer PRNG (reproduced in `sanity_buffer`), so
//! the whole table is reproducible from the specification without downloading
//! anything.
//!
//! Crate under test: `xxhash-rust` 0.8.18, `xxh3` feature, pinned with `=` in
//! `Cargo.toml`.

use g4_determinism::fixed::{self, Angle, Fx, Sq};
use g4_determinism::hash::{Enc, STATE_HASH_SEED, digest};
use g4_determinism::rng::{Stream, StreamRng};
use g4_determinism::{World, apportion};
use xxhash_rust::xxh3::{xxh3_64, xxh3_64_with_seed};

const PRIME32: u64 = 2_654_435_761;
const PRIME64: u64 = 11_400_714_785_074_694_797;

/// The upstream sanity buffer:
///
/// ```text
/// byteGen = PRIME32;
/// for i in 0..len { buffer[i] = byteGen >> 56; byteGen *= PRIME64; }
/// ```
fn sanity_buffer(len: usize) -> Vec<u8> {
    let mut byte_gen: u64 = PRIME32;
    let mut out = Vec::with_capacity(len);
    for _ in 0..len {
        out.push(u8::try_from(byte_gen >> 56).expect("top byte"));
        byte_gen = byte_gen.wrapping_mul(PRIME64);
    }
    out
}

/// `(len, seed, expected)` from upstream `XSUM_XXH3_testdata`. The comment on
/// each row is the size class it exercises, which is why these particular
/// lengths were chosen upstream: every code path in XXH3-64 is covered.
const XXH3_VECTORS: &[(usize, u64, u64)] = &[
    (0, 0, 0x2D06_8005_38D3_94C2),      // empty input, seed 0
    (0, PRIME64, 0xA8A6_B918_B2F0_364A), // empty input, seeded
    (1, 0, 0xC44B_DFF4_074E_ECDB),      // 1..3
    (1, PRIME64, 0x032B_E332_DD76_6EF8),
    (6, 0, 0x27B5_6A84_CD2D_7325), // 4..8
    (6, PRIME64, 0x8458_9C11_6AB5_9AB9),
    (12, 0, 0xA713_DAF0_DFBB_77E7), // 9..16
    (12, PRIME64, 0xE730_3E1B_2336_DE0E),
    (24, 0, 0xA3FE_70BF_9D35_10EB), // 17..32
    (24, PRIME64, 0x850E_80FC_35BD_D690),
    (48, 0, 0x397D_A259_ECBA_1F11), // 33..64
    (48, PRIME64, 0xADC2_CBAA_44AC_C616),
    (80, 0, 0xBCDE_FBBB_2C47_C90A), // 65..96
    (80, PRIME64, 0xC6DD_0CB6_9953_2E73),
    (195, 0, 0xCD94_217E_E362_EC3A), // 129..240
    (195, PRIME64, 0xBA68_003D_370C_B3D9),
    (403, 0, 0xCDEB_804D_65C6_DEA4), // >240, last stripe overlapping
    (403, PRIME64, 0x6259_F6EC_FD64_43FD),
    (512, 0, 0x617E_4959_9013_CB6B), // >240, ends on a stripe boundary
    (512, PRIME64, 0x3CE4_57DE_14C2_7708),
    (2048, 0, 0xDD59_E2C3_A5F0_38E0), // two blocks
    (2048, PRIME64, 0x66F8_1670_669A_BABC),
    (2240, 0, 0x6E73_A905_39CF_2948), // three blocks
    (2240, PRIME64, 0x757B_A848_7D1B_5247),
    (2367, 0, 0xCB37_AEB9_E5D3_61ED), // three blocks, last stripe overlapping
    (2367, PRIME64, 0xD2DB_3415_B942_B42A),
];

#[test]
fn xxh3_empty_input_reference_vector() {
    // The single vector that is quoted everywhere and is the anchor of the
    // whole table: XXH3_64bits("") == 0x2D06800538D394C2.
    assert_eq!(xxh3_64(b""), 0x2D06_8005_38D3_94C2);
    assert_eq!(xxh3_64_with_seed(b"", 0), 0x2D06_8005_38D3_94C2);
}

#[test]
fn xxh3_reference_vectors() {
    for &(len, seed, expected) in XXH3_VECTORS {
        let buf = sanity_buffer(len);
        let got = xxh3_64_with_seed(&buf, seed);
        assert_eq!(
            got, expected,
            "XXH3-64 mismatch at len={len} seed={seed:#018x}: got {got:#018x}, want {expected:#018x}"
        );
    }
}

#[test]
fn xxh3_unseeded_matches_seed_zero() {
    for &(len, _, _) in XXH3_VECTORS {
        let buf = sanity_buffer(len);
        assert_eq!(xxh3_64(&buf), xxh3_64_with_seed(&buf, 0), "len={len}");
    }
}

/// Not an upstream vector: our own seed's value over a fixed input, pinned so a
/// crate upgrade or a seed edit cannot pass unnoticed. If this moves, every
/// golden file in the project moved with it.
#[test]
fn project_seed_is_pinned() {
    assert_eq!(STATE_HASH_SEED, 0x5048_4152_4D4B_4F53);
    assert_eq!(STATE_HASH_SEED.to_be_bytes(), *b"PHARMKOS");
    // Literals, not `digest(x) == xxh3_64_with_seed(x, SEED)`: `digest` IS that
    // expression (src/hash.rs), so comparing the two is a tautology that cannot
    // fail under any edit to the seed, the crate or the function.
    assert_eq!(digest(b""), 0xFE1A_F732_B028_10AD);
    // Regression pin, recorded at day 1 of the spike.
    assert_eq!(digest(b"pharmakos/g4"), 0xE170_26C8_A5EA_4D30);
}

/// `Enc::default()` must carry the encoding version byte, like every other
/// construction path. A derived `Default` would hand back an empty buffer and an
/// encoder one prefix byte short of canonical — invisible at the call site.
#[test]
fn enc_default_carries_the_version_byte() {
    use g4_determinism::hash::ENCODING_VERSION;
    let d = Enc::default();
    assert_eq!(d.bytes(), &[ENCODING_VERSION], "Enc::default lost the version byte");
    assert_eq!(d.bytes(), Enc::with_capacity(0).bytes());
    let mut c = Enc::with_capacity(64);
    c.clear();
    assert_eq!(c.bytes(), d.bytes(), "clear and default disagree");
    assert_eq!(d.finish(), Enc::with_capacity(4096).finish());
}

// ---------------------------------------------------------------------------
// Fixed-point edge cases.
// ---------------------------------------------------------------------------

#[test]
fn fx_mul_floors_toward_negative_infinity() {
    let half = Fx(1 << 15);
    // -1 * 0.5 is exactly -0.5, representable, no rounding involved.
    assert_eq!(Fx::ONE.negate().mul_fx(half), Fx(-(1 << 15)));
    // An inexact product: 1 raw unit times a half is 0.5 raw units, and the
    // arithmetic shift floors, so positive rounds down and negative rounds away
    // from zero. This asymmetry is the documented behaviour; it is deterministic
    // and the sim is written around it.
    assert_eq!(Fx(1).mul_fx(half), Fx(0));
    assert_eq!(Fx(-1).mul_fx(half), Fx(-1));
}

#[test]
fn fx_division_truncates_toward_zero() {
    assert_eq!(Fx::ONE.div_fx(Fx::from_voxels(2)), Fx(1 << 15));
    assert_eq!(Fx(3).div_fx(Fx::from_voxels(2)), Fx(1));
    assert_eq!(Fx(-3).div_fx(Fx::from_voxels(2)), Fx(-1));
    // A negative divisor: truncation is still toward zero, so the magnitude is
    // the same and only the sign flips. `-3 / -2` is `+1`, not `+2`.
    assert_eq!(Fx(-3).div_fx(Fx::from_voxels(-2)), Fx(1));
    assert_eq!(Fx(3).div_fx(Fx::from_voxels(-2)), Fx(-1));
    assert_eq!(Fx::ONE.negate().div_fx(Fx::from_voxels(-2)), Fx(1 << 15));
    // Dividing by zero is a panic by construction, not a silent infinity.
    let r = std::panic::catch_unwind(|| Fx::ONE.div_fx(Fx::ZERO));
    assert!(r.is_err(), "Fx::div_fx by zero must panic");
}

/// `plus`, `minus`, `negate`, `mul_fx` and `scale` are the arithmetic the sim
/// actually runs (11 and 5 call sites for the first two alone). Each one has a
/// documented failure mode — `checked_*` or a `try_from` — and the point of
/// `overflow-checks = true` in every profile is that the failure is a panic, so
/// each failure mode is asserted rather than assumed.
#[test]
fn fx_add_sub_and_scale_panic_rather_than_wrap() {
    assert_eq!(Fx::from_voxels(3).plus(Fx::from_voxels(4)), Fx::from_voxels(7));
    assert_eq!(Fx::from_voxels(3).minus(Fx::from_voxels(4)), Fx::from_voxels(-1));
    assert_eq!(Fx::from_voxels(3).negate(), Fx::from_voxels(-3));
    assert_eq!(Fx::from_voxels(3).scale(-4), Fx::from_voxels(-12));
    assert_eq!(Fx::ZERO.scale(i32::MAX), Fx::ZERO);

    let cases: [(&str, fn()); 5] = [
        ("plus", || {
            let _ = Fx(i32::MAX).plus(Fx(1));
        }),
        ("minus", || {
            let _ = Fx(i32::MIN).minus(Fx(1));
        }),
        ("negate", || {
            let _ = Fx(i32::MIN).negate();
        }),
        ("mul_fx", || {
            // (2^24)^2 >> 16 == 2^32, one bit past i32.
            let _ = Fx(1 << 24).mul_fx(Fx(1 << 24));
        }),
        ("scale", || {
            let _ = Fx(i32::MAX).scale(2);
        }),
    ];
    for (name, f) in cases {
        let r = std::panic::catch_unwind(f);
        assert!(r.is_err(), "Fx::{name} must panic on overflow, not wrap");
    }
}

#[test]
fn fx_extremes_do_not_silently_wrap() {
    assert_eq!(Fx::from_voxels(i16::MIN).raw(), i32::from(i16::MIN) << 16);
    assert_eq!(Fx::from_voxels(i16::MAX).raw(), i32::from(i16::MAX) << 16);
    // i32::MIN has no positive counterpart; abs must not wrap silently.
    let r = std::panic::catch_unwind(|| Fx(i32::MIN).abs());
    assert!(r.is_err(), "Fx::abs(i32::MIN) must panic, not wrap");
}

#[test]
fn fx_clamp_is_total() {
    let lo = Fx::from_voxels(-10);
    let hi = Fx::from_voxels(10);
    assert_eq!(Fx::from_voxels(-99).clamp_to(lo, hi), lo);
    assert_eq!(Fx::from_voxels(99).clamp_to(lo, hi), hi);
    assert_eq!(Fx::ZERO.clamp_to(lo, hi), Fx::ZERO);
}

#[test]
fn sin_table_shape() {
    let t = fixed::sin_table();
    assert_eq!(t.len(), 4096);
    assert_eq!(t[0], 0, "sin(0)");
    assert_eq!(t[1024], 65_536, "sin(pi/2) == 1.0 exactly");
    assert_eq!(t[2048], 0, "sin(pi)");
    assert_eq!(t[3072], -65_536, "sin(3pi/2) == -1.0 exactly");
    // Odd symmetry, exact, because the second half is built by negation.
    for i in 1..2048 {
        assert_eq!(t[i], -t[i + 2048], "odd symmetry at {i}");
    }
    // Non-decreasing over the first quarter: that is what makes the predicate in
    // Angle::from_delta monotone and the binary search total. Strict
    // monotonicity does NOT hold near the peak — sin(x) is flat there and Q16.16
    // resolution is 1/65_536, so the last few entries repeat. Asserting the
    // weaker property is the correct contract, not a concession.
    for i in 0..1024 {
        assert!(t[i] <= t[i + 1], "not monotone at {i}");
    }
    // Strictly increasing over the octant the search actually walks, 0..=512.
    for i in 0..512 {
        assert!(t[i] < t[i + 1], "octant not strictly monotone at {i}");
    }
    // The flat top is real and is exactly where it should be.
    assert_eq!(t[1023], t[1024], "sin is expected to saturate at the peak");
    // sin^2 + cos^2 == 1 to within a small fixed-point tolerance.
    for i in (0..4096).step_by(37) {
        let a = Angle(u16::try_from(i << 4).unwrap());
        let s = i64::from(fixed::sin(a).raw());
        let c = i64::from(fixed::cos(a).raw());
        let one: i64 = 1 << 32;
        let n = s * s + c * c;
        assert!((n - one).abs() < (1 << 18), "unit circle at {i}: {n} vs {one}");
    }
}

#[test]
fn angle_from_delta_round_trips_through_the_table() {
    // Every table step, reconstructed from its own cos/sin pair.
    for i in (0..4096).step_by(7) {
        let a = Angle(u16::try_from(i << 4).unwrap());
        let r = Fx::from_voxels(1000);
        let x = fixed::cos(a).mul_fx(r);
        let y = fixed::sin(a).mul_fx(r);
        let back = Angle::from_delta(x, y);
        let diff = i32::from(back.0).wrapping_sub(i32::from(a.0));
        let diff = if diff > 32_768 { diff - 65_536 } else { diff };
        assert!(diff.abs() <= 16, "angle {i}: recovered {} (delta {diff})", back.0);
    }
}

#[test]
fn angle_from_delta_axes_are_exact() {
    assert_eq!(Angle::from_delta(Fx::from_voxels(5), Fx::ZERO), Angle(0));
    assert_eq!(Angle::from_delta(Fx::ZERO, Fx::from_voxels(5)), Angle(16_384));
    assert_eq!(Angle::from_delta(Fx::from_voxels(-5), Fx::ZERO), Angle(32_768));
    assert_eq!(Angle::from_delta(Fx::ZERO, Fx::from_voxels(-5)), Angle(49_152));
    assert_eq!(Angle::from_delta(Fx::ZERO, Fx::ZERO), Angle(0));
}

#[test]
fn turn_toward_is_total_and_shortest() {
    let a = Angle(0);
    assert_eq!(a.turn_toward(Angle(100), 512), Angle(100));
    assert_eq!(a.turn_toward(Angle(5_000), 512), Angle(512));
    assert_eq!(a.turn_toward(Angle(60_000), 512), Angle(65_024));
    // Exactly half a turn: the positive direction wins, by definition, so two
    // machines cannot disagree.
    assert_eq!(a.turn_toward(Angle(32_768), 512), Angle(512));
    assert_eq!(a.turn_toward(Angle(0), 512), Angle(0));
}

#[test]
fn sq_distance_is_symmetric_and_exact() {
    let a = [Fx::from_voxels(3), Fx::from_voxels(4), Fx::ZERO];
    let z = [Fx::ZERO; 3];
    assert_eq!(Sq::between(a, z), Sq::between(z, a));
    assert_eq!(Sq::between(a, z), Sq::of_radius(Fx::from_voxels(5)));
    // The map-extent bound in the doc comment: no overflow at the corners.
    let c1 = [Fx::from_voxels(1024), Fx::from_voxels(1024), Fx::from_voxels(1024)];
    let c2 = [
        Fx::from_voxels(-1024),
        Fx::from_voxels(-1024),
        Fx::from_voxels(-1024),
    ];
    let d = Sq::between(c1, c2);
    assert!(d.0 > 0, "corner-to-corner distance overflowed");
}

// ---------------------------------------------------------------------------
// Largest-remainder apportionment, ties to the lowest seat id.
// ---------------------------------------------------------------------------

#[test]
fn apportion_sums_to_the_bounty() {
    let cases: &[(i64, &[(u8, u32)])] = &[
        (250, &[(0, 1), (1, 1), (2, 1)]),
        (250, &[(0, 7), (1, 11), (2, 13)]),
        (1_200, &[(1, 149), (2, 1)]),
        (100, &[(0, 1)]),
        (7, &[(0, 1), (1, 1), (2, 1)]),
    ];
    for &(bounty, entries) in cases {
        let shares = apportion(bounty, entries);
        let total: i64 = shares.iter().map(|s| s.1).sum();
        assert_eq!(total, bounty, "entries {entries:?}");
        assert_eq!(shares.len(), entries.len());
        for (i, s) in shares.iter().enumerate() {
            assert_eq!(s.0, entries[i].0, "share order must follow entry order");
        }
    }
}

#[test]
fn apportion_breaks_ties_to_the_lowest_seat_id() {
    // Three equal contributors and a bounty of 100: quotas are 33 each, one unit
    // is left over, and every remainder is equal. The lowest seat id takes it.
    let shares = apportion(100, &[(0, 1), (1, 1), (2, 1)]);
    assert_eq!(shares, vec![(0, 34), (1, 33), (2, 33)]);

    // The same, with the entries presented in a different order: the result must
    // depend on the seat id, not on the order the entries arrived in.
    let shares = apportion(100, &[(2, 1), (1, 1), (0, 1)]);
    let mut by_seat = shares.clone();
    by_seat.sort_unstable_by_key(|s| s.0);
    assert_eq!(by_seat, vec![(0, 34), (1, 33), (2, 33)]);

    // Two-way tie: 10 over two equal contributors is exact, no remainder.
    assert_eq!(apportion(10, &[(0, 5), (1, 5)]), vec![(0, 5), (1, 5)]);
    // 11 over two equal contributors: the odd unit goes to seat 0.
    assert_eq!(apportion(11, &[(0, 5), (1, 5)]), vec![(0, 6), (1, 5)]);
}

/// `Credits::record` directly, including the branch the sim cannot reach.
///
/// With four seats and no friendly fire an asset has exactly three possible
/// damagers, so a fourth distinct seat never arrives and the eviction branch is
/// dead code *in the toy* — but the rule graduates into the product, where seat
/// counts are not fixed at four, so it is pinned here rather than left untested.
#[test]
fn credits_record_caps_and_evicts_the_weakest() {
    use g4_determinism::{Credits, MAX_CREDITS};

    // Accumulation, and the list stays sorted by seat whatever the arrival order.
    let mut c = Credits::default();
    c.record(2, 10);
    c.record(0, 5);
    c.record(2, 7);
    assert_eq!(c.entries, vec![(0, 5), (2, 17)]);

    // The cap binds at MAX_CREDITS distinct seats.
    let mut c = Credits::default();
    c.record(0, 100);
    c.record(1, 50);
    c.record(2, 30);
    assert_eq!(c.entries.len(), MAX_CREDITS);
    // A fourth seat weaker than the weakest entry is refused outright.
    c.record(3, 10);
    assert_eq!(c.entries, vec![(0, 100), (1, 50), (2, 30)]);
    // A fourth seat stronger than the weakest displaces exactly that entry.
    c.record(3, 40);
    assert_eq!(c.entries, vec![(0, 100), (1, 50), (3, 40)]);

    // The damage tie, which is the part the comment and the code used to
    // disagree about. Seats 1 and 2 are equally small; "ties to the lowest seat
    // id" means the lowest seat is FAVOURED, so seat 2 is the one displaced.
    let mut c = Credits::default();
    c.record(0, 100);
    c.record(1, 30);
    c.record(2, 30);
    c.record(3, 40);
    assert_eq!(
        c.entries,
        vec![(0, 100), (1, 30), (3, 40)],
        "a damage tie must evict the highest seat id, leaving the lowest in place"
    );

    // Equal to the weakest is not "stronger than": no displacement.
    let mut c = Credits::default();
    c.record(0, 100);
    c.record(1, 30);
    c.record(2, 30);
    c.record(3, 30);
    assert_eq!(c.entries, vec![(0, 100), (1, 30), (2, 30)]);

    // An existing seat always accumulates, even when the list is full.
    let mut c = Credits::default();
    c.record(0, 1);
    c.record(1, 1);
    c.record(2, 1);
    c.record(1, 99);
    assert_eq!(c.entries, vec![(0, 1), (1, 100), (2, 1)]);
}

#[test]
fn apportion_rejects_degenerate_input() {
    assert!(apportion(0, &[(0, 1)]).is_empty());
    assert!(apportion(-5, &[(0, 1)]).is_empty());
    assert!(apportion(100, &[]).is_empty());
    assert!(apportion(100, &[(0, 0), (1, 0)]).is_empty());
}

// ---------------------------------------------------------------------------
// RNG streams.
// ---------------------------------------------------------------------------

#[test]
fn streams_are_independent_and_positional() {
    let seed = 0x0102_0304_0506_0708;
    let mut a = StreamRng::new(seed, Stream::Combat, 10, 1, 7);
    let mut b = StreamRng::new(seed, Stream::Combat, 10, 1, 7);
    assert_eq!(a.next_u64(), b.next_u64(), "same position, same value");

    // Different stream, same position: different value.
    let mut c = StreamRng::new(seed, Stream::Spawn, 10, 1, 7);
    let mut d = StreamRng::new(seed, Stream::Map, 10, 1, 7);
    let (x, y, z) = (a.next_u64(), c.next_u64(), d.next_u64());
    assert_ne!(x, y);
    assert_ne!(y, z);
    assert_ne!(x, z);

    // Stream ids are explicit, not discriminants.
    assert_eq!(Stream::Combat.id(), 1);
    assert_eq!(Stream::Spawn.id(), 2);
    assert_eq!(Stream::Map.id(), 3);
}

/// Golden pins for the split-RNG construction — frozen choice (3) of the plan's
/// section 8, and the thing harness part 1 turns into a contract.
///
/// Everything else about the RNG is a self-comparison: two generators at the
/// same position agree, three streams disagree. None of that pins `GOLDEN`, the
/// two SplitMix64 multipliers, or the multiply-shift in `range_i32`. Editing any
/// of them would leave every other test green while silently moving every hash
/// in the project; the only other thing that would catch it is the trace digest,
/// which lives in a document rather than in an assertion.
///
/// Values measured on this build. If one moves, the construction moved, and so
/// did every golden file that was ever stamped with it.
#[test]
fn rng_construction_is_pinned() {
    use g4_determinism::rng::mix64;

    // The SplitMix64 finaliser, on its own. mix64(0) == 0 is a property of the
    // construction (every step is a xor-shift or a multiply), not a measurement.
    assert_eq!(mix64(0), 0);
    assert_eq!(mix64(1), 0x5692_161D_100B_05E5);
    // GOLDEN itself, which is the multiplier every position term goes through.
    assert_eq!(mix64(0x9E37_79B9_7F4A_7C15), 0xE220_A839_7B1D_CDAF);

    // The whole construction: seed, stream, tick, seat, sub -> first two draws.
    let mut r = StreamRng::new(0x0102_0304_0506_0708, Stream::Combat, 10, 1, 7);
    assert_eq!(r.next_u64(), 0xCDC6_5EE9_1829_2C78);
    assert_eq!(r.next_u64(), 0x1005_52F8_977C_9F98);

    // The stream-id mixing: a different stream at the same position.
    let mut s = StreamRng::new(0x0102_0304_0506_0708, Stream::Spawn, 10, 1, 7);
    assert_eq!(s.next_u64(), 0x0A84_9AA1_ED23_D46C);

    // Seed 0, position 0, every field zero: the corner the construction is most
    // likely to collapse at if a term is dropped.
    let mut z = StreamRng::new(0, Stream::Combat, 0, 0, 0);
    assert_eq!(z.next_u64(), 0x1957_A760_4E21_5178);

    // `range_i32` is a second contract on top of the stream: the multiply-shift
    // maps a draw to a bounded value, and the residual bias is part of the
    // frozen behaviour, not an implementation detail.
    let mut q = StreamRng::new(0x0102_0304_0506_0708, Stream::Combat, 10, 1, 7);
    let seq: Vec<i32> = (0..8).map(|_| q.range_i32(-3, 3)).collect();
    assert_eq!(
        seq,
        vec![2, -3, 3, -2, 0, -2, -1, 2],
        "range_i32(-3, 3) at a fixed position moved"
    );
}

#[test]
fn range_is_inside_its_bounds() {
    let mut r = StreamRng::new(0xDEAD_BEEF, Stream::Combat, 0, 0, 0);
    for _ in 0..10_000 {
        let v = r.range_i32(-3, 3);
        assert!((-3..=3).contains(&v), "out of range: {v}");
    }
    let mut r2 = StreamRng::new(1, Stream::Spawn, 0, 0, 0);
    for _ in 0..1_000 {
        let v = r2.range_i32(i32::MIN / 2, i32::MAX / 2);
        assert!((i32::MIN / 2..=i32::MAX / 2).contains(&v));
    }
    let mut r3 = StreamRng::new(1, Stream::Map, 0, 0, 0);
    assert_eq!(r3.range_i32(5, 5), 5, "degenerate range");
    // The full i32 span: `hi - lo + 1` is exactly 2^32, the only value that
    // stresses the u64 -> u128 widening in range_i32 (a u32 span would wrap to
    // zero, and the multiply-shift would collapse to lo).
    let mut r4 = StreamRng::new(0xA5A5_A5A5, Stream::Combat, 7, 2, 9);
    let mut saw_negative = false;
    let mut saw_positive = false;
    for _ in 0..1_000 {
        let v = r4.range_i32(i32::MIN, i32::MAX);
        saw_negative |= v < 0;
        saw_positive |= v > 0;
    }
    assert!(
        saw_negative && saw_positive,
        "range_i32 over the full i32 span collapsed to one side"
    );
}

// ---------------------------------------------------------------------------
// The sim itself: the properties the hash contract rests on.
// ---------------------------------------------------------------------------

#[test]
fn canonical_encoding_is_stable_and_fixed_stride() {
    let w = World::new(g4_determinism::MATCH_SEEDS[0]);
    let mut e1 = Enc::with_capacity(1024);
    let mut e2 = Enc::with_capacity(1024);
    w.encode(&mut e1);
    w.encode(&mut e2);
    assert_eq!(e1.bytes(), e2.bytes(), "encoding is not a pure function");
    assert_eq!(e1.finish(), w.state_hash());

    // 1 version byte + 8 seed + 4 tick + 4 deaths
    // + 4 len + UNIT_COUNT * (4+1+12+2+4+5+2)
    // + 4 len + BEACON_COUNT * (4+1+12+4+8+4)
    // + 4 len + SEATS * (1+8+4+4)
    // + 4 len (credits, empty at tick 0)
    let expected = 1
        + 8
        + 4
        + 4
        + 4
        + g4_determinism::UNIT_COUNT * 30
        + 4
        + g4_determinism::BEACON_COUNT * 33
        + 4
        + g4_determinism::SEATS * 17
        + 4;
    assert_eq!(e1.bytes().len(), expected, "canonical encoding stride moved");
    // The number that goes into the plan's Results section, spelled out so a
    // table shape change cannot quietly move it: 6,497 bytes at tick 0 with
    // 200 units, 12 beacons and 4 seats.
    assert_eq!(e1.bytes().len(), 6_497, "tick-0 canonical encoding length");
}

#[test]
fn same_seed_same_trace() {
    let a = g4_determinism::trace_match(g4_determinism::MATCH_SEEDS[0], 300);
    let b = g4_determinism::trace_match(g4_determinism::MATCH_SEEDS[0], 300);
    assert_eq!(a, b);
}

#[test]
fn different_seeds_diverge() {
    let a = g4_determinism::trace_match(g4_determinism::MATCH_SEEDS[0], 200);
    let b = g4_determinism::trace_match(g4_determinism::MATCH_SEEDS[1], 200);
    assert_ne!(a, b, "two seeds produced identical traces");
}

#[test]
fn the_sim_actually_does_something() {
    // A trace of 9,600 identical hashes would pass every determinism check in
    // the plan and prove nothing at all, so the workload itself is asserted.
    let ticks = g4_determinism::MATCH_TICKS;
    let t = g4_determinism::trace_match(g4_determinism::MATCH_SEEDS[0], ticks);
    let mut uniq = t.clone();
    uniq.sort_unstable();
    uniq.dedup();
    let n = usize::try_from(ticks).unwrap();
    assert!(
        uniq.len() * 100 / n >= 99,
        "only {} distinct hashes in {n} ticks — the state stops moving",
        uniq.len()
    );

    let mut w = World::new(g4_determinism::MATCH_SEEDS[0]);
    let mut first_death: Option<u32> = None;
    for _ in 0..ticks {
        w.step();
        if first_death.is_none() && w.deaths > 0 {
            first_death = Some(w.tick);
        }
    }
    println!(
        "liveliness: deaths={} first_death_tick={:?} kills={:?} cash={:?} \
         beacons_destroyed={} units_alive={} credit_entries={}",
        w.deaths,
        first_death,
        w.seats.iter().map(|s| s.kills).collect::<Vec<_>>(),
        w.seats.iter().map(|s| s.cash).collect::<Vec<_>>(),
        (0..w.beacons.len()).filter(|&i| !w.beacons.alive(i)).count(),
        (0..w.units.len()).filter(|&i| w.units.alive(i)).count(),
        w.credits.len(),
    );
    assert!(w.deaths > 0, "nothing died in a whole match");
    assert!(!w.credits.is_empty(), "no kill-credit counters were created");
    assert!(
        w.seats.iter().all(|s| s.kills > 0),
        "some seat was never credited a kill: {:?}",
        w.seats.iter().map(|s| s.kills).collect::<Vec<_>>()
    );
    // Largest-remainder apportionment only matters if several seats damage the
    // same asset, so assert that the three-way case actually occurs.
    let mut w2 = World::new(g4_determinism::MATCH_SEEDS[1]);
    let mut multi = 0usize;
    let mut full = 0usize;
    let mut widest = 0usize;
    for _ in 0..ticks {
        w2.step();
        for (_, c) in w2.credits.iter() {
            if c.entries.len() >= 2 {
                multi += 1;
            }
            if c.entries.len() >= g4_determinism::MAX_CREDITS {
                full += 1;
            }
            widest = widest.max(c.entries.len());
        }
    }
    assert!(multi > 0, "no asset was ever damaged by two different seats");
    // The reason SEATS is 4. With three seats an asset has only two possible
    // damagers, so the MAX_CREDITS cap could never bind and the three-entry
    // largest-remainder apportionment — the case the plan calls out by name —
    // would never run in the trace at all.
    println!("credit coverage: widest={widest} full_observations={full}");
    assert_eq!(
        widest,
        g4_determinism::MAX_CREDITS,
        "the MAX_CREDITS cap is not exercised by the toy"
    );
}

/// The ten-match trace digest, as an assertion rather than as a number in a
/// document.
///
/// `bin/run` prints this digest, and section 9 of the plan records it — but a
/// number in a document is not a regression check, and until the cross-OS
/// workflow is installed the digest is the only thing standing between an
/// accidental sim change and a silently different project-wide hash. Rendering
/// is byte-for-byte what `run` writes (binary mode, explicit `\n`), so the two
/// cannot drift apart.
///
/// `#[ignore]`d because it runs the full 96,000 ticks: ~1.4 s in release but
/// ~30 s in debug. Run it with `cargo test --release -- --ignored`; the CI
/// workflow does exactly that.
#[test]
#[ignore = "full 96,000-tick run; cargo test --release -- --ignored"]
fn ten_match_trace_digest_is_pinned() {
    use g4_determinism::hash::hex;

    let mut buf: Vec<u8> = Vec::with_capacity(2_400_000);
    for (m, &seed) in g4_determinism::MATCH_SEEDS.iter().enumerate() {
        let trace = g4_determinism::trace_match(seed, g4_determinism::MATCH_TICKS);
        for (t, h) in trace.iter().enumerate() {
            buf.extend_from_slice(m.to_string().as_bytes());
            buf.push(b'\t');
            buf.extend_from_slice(t.to_string().as_bytes());
            buf.push(b'\t');
            buf.extend_from_slice(hex(*h).as_bytes());
            buf.push(b'\n');
        }
    }
    // The digest covers the 96,000 tick lines only; `run`'s file is 24 bytes
    // longer because it appends its own `digest<TAB>...<LF>` line afterwards.
    assert_eq!(buf.len(), 2_292_900, "trace byte length moved");
    assert_eq!(
        hex(digest(&buf)),
        "340a30048a380595",
        "the ten-match trace digest moved — every golden stamped with it moved too"
    );
}

#[test]
fn snapshot_round_trips_in_process() {
    // The in-process half of G4-b. The cross-process half is `bin/roundtrip`.
    //
    // 500 ticks, not 137: the first death lands around tick 313, so at 137 the
    // credit table is empty for every seed and the round trip never exercises
    // the c_asset/c_n/c_seat/c_dmg run-length encoding or the `cursor` walk in
    // `Snapshot::restore` — the one part of the projection that is not a 1:1
    // field copy, and the likeliest place for a restore to lose state.
    let mut w = World::new(g4_determinism::MATCH_SEEDS[2]);
    for _ in 0..500 {
        w.step();
    }
    assert!(
        !w.credits.is_empty(),
        "snapshot test must cover a non-empty credit table; retune the tick count"
    );
    let snap = g4_determinism::snapshot::Snapshot::capture(&w);
    let back = snap.restore();
    assert_eq!(back.state_hash(), w.state_hash(), "snapshot is not hash-transparent");
    assert_eq!(back, w, "snapshot lost state the hash does not cover");

    let mut a = w.clone();
    let mut b = back;
    for _ in 0..200 {
        a.step();
        b.step();
        assert_eq!(a.state_hash(), b.state_hash(), "restored world diverged");
    }
}

#[cfg(any(feature = "snap-rkyv", feature = "snap-postcard"))]
#[test]
fn snapshot_bytes_round_trip() {
    let mut w = World::new(g4_determinism::MATCH_SEEDS[3]);
    for _ in 0..500 {
        w.step();
    }
    let snap = g4_determinism::snapshot::Snapshot::capture(&w);
    let bytes = g4_determinism::snapshot::encode(&snap);
    // Encoding is a pure function of the value: the same snapshot twice must
    // produce the same bytes, or saves are not comparable across machines.
    assert_eq!(bytes, g4_determinism::snapshot::encode(&snap));
    let back = g4_determinism::snapshot::decode(&bytes);
    assert_eq!(back, snap);
    assert_eq!(back.restore().state_hash(), w.state_hash());
}

#[cfg(feature = "research")]
#[test]
fn fork_is_equivalent_to_stepping() {
    let mut w = World::new(g4_determinism::MATCH_SEEDS[4]);
    for _ in 0..100 {
        w.step();
    }
    let before = w.state_hash();
    let (_, child) = g4_determinism::fork::fork_and_step(&w, 50);
    assert_eq!(w.state_hash(), before, "forking perturbed the parent");

    let mut parent = w.clone();
    let mut want = Vec::new();
    for _ in 0..50 {
        parent.step();
        want.push(parent.state_hash());
    }
    assert_eq!(child, want);
}
